### ISSUE TITLE
should some special characters (like ^ + | <>) be skew in italic style?

### ISSUE THREAD

**Issue by namnm** [adobe-fonts/source-code-pro#100]
Consolas and some other programming fonts make them skew and I feel it look better. What do you think?

**Comment by emansije** [comment]
The `|` character might get too close to the `/`, generating unnecessary confusion, but the rest should be ok.

**Comment by frankrolf** [comment]
Normally mathematical characters Don’t skew in Italics, but it depends a lot on taste.

**Comment by pauldhunt** [comment]
if you don't like it, branch it. that's the beauty of open source.

On Aug 16, 2015, at 1:58 PM, Frank Grie?hammer <notifications@github.com<mailto:notifications@github.com>> wrote:

Normally mathematical characters Don't skew in Italics, but it depends a lot on taste.


> On Aug 16, 2015, at 12:49 PM, Emanuel de Jesus <notifications@github.com<mailto:notifications@github.com>> wrote:
>
> The | character might get too close to the /, generating unnecessary confusion, but the rest should be ok.
>
> ?
> Reply to this email directly or view it on GitHub.
>

-
