### ISSUE TITLE
Italic cyrillic is too slant compared to other characters

### ISSUE THREAD

**Issue by plashenkov** [adobe-fonts/source-code-pro#102]
Currently cyrillic italic style is too slant if compared to other characters. Here is a screenshot:

![1](https://cloud.githubusercontent.com/assets/2331932/9270472/e2280d4e-4293-11e5-8ff9-5e155f0825b1.png)

P.S. Thank you for the super wonderful font!

**Comment by frankrolf** [comment]
Source Code Pro Italic currently does not support Cyrillic yet. 
What you are seeing is an auto-slanted version of the Upright style.
