### ISSUE TITLE
Downloading builds

### ISSUE THREAD

**Issue by dukedorje** [adobe-fonts/source-code-pro#107]
I am having trouble locating recent builds.  I don't have Adobe Font Development Kit, but I'm a programmer and I'd also love to have access to the new PowerLine symbols.  Under "releases" I am only seeing source code downloads, and some limited builds that say "for testing only" etc.

Where do I find recent builds for this font?

**Comment by pauldhunt** [comment]
it seems you may be looking at the wrong page? these are the fonts you were looking for:
https://github.com/adobe-fonts/source-code-pro/releases

**Comment by dukedorje** [comment]
Yep, I downloaded the master branch as a zip earlier, and on the releases page I saw "Source Code (zip)" ... I assumed it was the source code again, rather than a build of Source Code.  :sweat_smile:
