### ISSUE TITLE
Typo in source-code-pro.css: WOFF2/OTF/SourceCodePro-ExtraLight.ttf.woff2

### ISSUE THREAD

**Issue by rutsky** [adobe-fonts/source-code-pro#110]
`source-code-pro.css` in the [latest release](https://github.com/adobe-fonts/source-code-pro/releases/tag/2.010R-ro%2F1.030R-it) includes WOFF2 fonts using incorrect path, like:

```
url('WOFF2/OTF/SourceCodePro-ExtraLight.ttf.woff2') format('woff2'),
```

In `WOFF2/OTF/` directory there are only `*.otf.woff2` files, not `*.ttf.woff2` files.

I believe `WOFF2/OTF/*.ttf.woff2` should be replaced with `WOFF2/OTF/*.otf.woff2` in `source-code-pro.css`.

**Comment by miguelsousa** [comment]
That got fixed by b46816fb0d20d26746808e5845dc5c5e9e2251b6

**Comment by rutsky** [comment]
Thanks @miguelsousa!

Is next tagged release that will include this fix is planned? If yes, when it will be?

I don't want to include `release` branch in Bower, but instead would like to use specific release.

**Comment by miguelsousa** [comment]
@rutsky I'll try to move the tag up so it includes that particular commit.

**Comment by miguelsousa** [comment]
The tag `2.010R-ro/1.030R-it` now includes the commit that fixed the font file paths.
