### ISSUE TITLE
Change font to look nice in apps that don't support DirectWrite

### ISSUE THREAD

**Issue by mnaoumov** [adobe-fonts/source-code-pro#116]
When I use this font in Sublime Text by default it looks blurry. Look at the quote character.

![Sublime Text 3 with default settings](https://cloud.githubusercontent.com/assets/735878/11953212/1bbf4fda-a8a7-11e5-8813-89d40b4beb07.png)

But if I enable DirectWrite it looks much better

![Sublime Text 3 with DirectWrite](https://cloud.githubusercontent.com/assets/735878/11953229/3e372722-a8a7-11e5-9346-16296857705b.png)

But if I want to this the font in apps that don't support DirectWrite yet, e.g. ConEmu, I don't have a way to make this font look better.

![ConEmu](https://cloud.githubusercontent.com/assets/735878/11953261/7079f160-a8a7-11e5-8323-ee93f8163b29.png
)

**Comment by miguelsousa** [comment]
@mnaoumov which fonts did you use, the TTFs or the OTFs? On Windows without DirectWrite, the TTFs may give you better results.

**Comment by mnaoumov** [comment]
@miguelsousa Thanks a lot! I installed the font via Chocolatey https://chocolatey.org/packages/SourceCodePro and it installs OTF only. I removed OTF and installed TTF and it looks smooth now.
