### ISSUE TITLE
peseta glyph

### ISSUE THREAD

**Issue by srl295** [adobe-fonts/source-code-pro#117]
- U+20A7, `₧` in SourceCodePro shows as "P" overstruck with "—" in SourceCodePro. It looks similar to U+20B1,  "₱" but with one dash instead of two.
- apparently, this was a glyph variation going back to [Unicode 1.0.0](http://www.unicode.org/versions/Unicode1.0.0/)
- But as in  [L2-00/013](http://www.unicode.org/L2/L2000/00013-n2156.pdf) the charts reflect "Change glyph shape of U-20A7 PESETA SIGN to “Pts”  - noted in minutes [L2-00/005](http://www.unicode.org/L2/L2000/00005.htm)
- current charts as for [8.0](http://unicode.org/charts/PDF/U20A0.pdf) refolect the "Pts" shape.
- Note, this symbol is for the obsolete currency `ESP`

Also, SCP isn't alone in this usage. Other fonts on my mac have the "old" shape instead of the "Pts".

**Comment by pauldhunt** [comment]
@srl295 so for an obsolete currency sign, is it ok to use an obsolete glyph design?

**Comment by frankrolf** [comment]
The struck P-symbol ist often preferred since it allows currency symbols to have the same width as the tabular figures (which is common practice). Much more difficult to do that with a combination of letters like `Pts`.

**Comment by fitojb** [comment]
Oh! That seems to be the reason why the Roboto font has `Pt` instead of `Pts` as the symbol for this currency, so that the symbol can be narrow.

**Comment by codeman38** [comment]
Incidentally, this is equivalent to character 0x9E in MS-DOS code page 437, for which most video cards and printers went with the `Pt` rendering. (I vaguely recall having seen one or two that went with `Pts` instead, but maybe my memory is playing tricks on me?)

**Comment by srl295** [comment]
@pauldhunt well, the codepoint isn't obsolete, just the currency. I hit this because we have CLDR data which contains this point.

@frankrolf yes but there's `₱` for that - U+20B1. That was added 16 years ago now.

**Comment by pauldhunt** [comment]
@srl295 so is there a proposal for this issue? or is it just an FYI? (i never implied that the codepoint was obsolete, just that the currency and the current glyph form in Source Sans were).

**Comment by srl295** [comment]
@pauldhunt sure, I would propose that the glyph is changed to `Pts` reflecting current Unicode charts for U+20A7

**Comment by pauldhunt** [comment]
I’ll look into making the Pt version work in the next revision (but not Pts, that’s where I draw the line, or remove the line, or whatever).

**Comment by srl295** [comment]
@pauldhunt different strokes for different folks… so to speak

**Comment by frankrolf** [comment]
I just came across this document:

> […] the Spanish Peseta has two possible forms. One is an uppercase 'P' with a horizontal bar traveling through the upper bowl of the 'P'. The second and most common design supplied in fonts is the 'Pts' form of a ligature made from the uppercase 'P' lowercase 't' and lowercase 's'.

https://www.microsoft.com/typography/developers/fdsspec/monetary.htm

**Comment by moyogo** [comment]
@frankrolf that page is from 1998. L2-00/013 is from 2000. Unicode was fixed, Microsoft should fix that page.

**Comment by frankrolf** [comment]
@moyogo Hah. Good eye.
At least it says “last updated 26 February 2001” ;-)
