### ISSUE TITLE
Ampersand (&) is missing from Bold font

### ISSUE THREAD

**Issue by andrewranney** [adobe-fonts/source-code-pro#118]
I've been using this font for my terminal SSH client for years and just noticed this week the Bold font is missing the ampersand (&) symbol.  As shown in the attached image the terminal client and Notepad++ do not display & when bold font is used.  The character is there when copied and pasted to a new application that isn't using this the bold version of this font.

![bold font is missing ampersand](https://cloud.githubusercontent.com/assets/15218726/13532650/766b837c-e1e1-11e5-96a8-88834031189e.jpg)

![image](https://cloud.githubusercontent.com/assets/15218726/13532687/a6764534-e1e1-11e5-9e23-d751e8193614.png)

**Comment by miguelsousa** [comment]
This was fixed long ago (see issue #11). Update to the [latest version](https://github.com/adobe-fonts/source-code-pro/releases/latest).
