### ISSUE TITLE
Fraction characters have zero width

### ISSUE THREAD

**Issue by nanoant** [adobe-fonts/source-code-pro#121]
I presume this problem comes from `widthAdjust.fea` where `@FRACTION_GLYPHS = [fraction divisionslash slash.frac]` get their widths zeroed for some reason. Guessing the reason is combining them with other characters, eg. `threequarters`. However as a nasty side-effect the standalone versions have zero width and look really bad.

I don't think this is expected behavior, especially that other monospaced fonts do not exhibit such behavior. 

I came across this problem using Source Code Pro (Hasklig) for editing Go language assembly, using division slash U+2215 as a module path separator.
![zrzut ekranu 2016-04-18 o 12 35 30](https://cloud.githubusercontent.com/assets/103067/14601376/10d931d6-0562-11e6-8e30-48402066f1e9.png)

**Comment by pauldhunt** [comment]
I will update this behavior to be localized to the fractions feature and not applied by default.
