### ISSUE TITLE
Downloading the font

### ISSUE THREAD

**Issue by andrewrynhard** [adobe-fonts/source-code-pro#123]
The README provides a link to `Download the fonts (OTF, TTF, WOFF, WOFF2, EOT)` but there is only the source code. Is compiling from source the only way to get the font?

**Comment by andrewrynhard** [comment]
Just downloaded the 'Source code'. Turns out it has the fonts but is not actually the 'Source code'. Misleading and confusing.

**Comment by frankrolf** [comment]
Unfortunately, that’s automatic wording coming from Github. Do you know how to change it?

**Comment by Defman21** [comment]
There's no way to change this word.

**Comment by andrewrynhard** [comment]
Perhaps it should be mentioned in the README?

**Comment by miguelsousa** [comment]
I've added a comment about it on the Release Notes.
