### ISSUE TITLE
Make #1 great again

### ISSUE THREAD

**Issue by Luxsi** [adobe-fonts/source-code-pro#126]
_**Arguably this isn't a huge issue**_, but I'd be surprised if I'm the only one.
The number one in SCP, at least at small sizes, looks identical to the lower-case 'L' from almost any other code font. Consider someone is just glancing at your code, unfamiliar with the font... Confusing. I think it's a valid concern, especially given this font wants to be 'perfect'.

My suggestion is that the 1's 'hat' would be tilted 45° and extended long enough that it's easily and intuitively recognizable at any font size and render style.

**Comment by miguelsousa** [comment]
@Luxsi please provide some images of _[t]he number one [...] looks identical to the lower-case 'L' from almost any other code font_ to make your case stronger.

**Comment by Luxsi** [comment]
@miguelsousa By 'code font' I mean console/IDE/monospace font, you name it.
Get a reference image of SCP '1' and low-case L 'l', go to this site: http://app.programmingfonts.org/ type out "1 l" in the text and scroll through the fonts. 31/57 of those fonts low-case L looks like SCP 1, or at least have a distinguishable '1'. You can google for more "best programming fonts" and compare. It should quickly become obvious.

I think the problem might be Windows where most of the default fonts used are as I describe, where as Linux style fonts mostly uses L's that look like inverted and stretched s'. Therefore causing less confusion.

@pauldhunt 

> but this is a common issue with almost all Latin fonts

Isn't that just more of a reason _NOT_ to do it. I just started using this font a while ago and it was the only issue that struck me, in this otherwise practical and beautiful font.

> IMO I feel that the differentiation of the forms for 1 and l is sufficient in the Source Code design so that they are not confusable for each other.

My main concern was to distinguish the SCP '1' from other fonts 'l', not within the font. But even within, I think the 1 could easily pass as a letter. Only at large renders or certain anti-aliases does it look like a 'one', but I would argue most code is viewed at small sizes around 9-12

An ideal example would be _Anonymous Pro_: (IMO not a pretty font, but gets the point) http://www.slant.co/topics/67/viewpoints/1/~programming-fonts~anonymous-pro where you can tell the '1' is a one from across the room (and also an example of the 'l' looking like SCP '1'). A long, significantly sloped hat would remove all ambiguity. Also look at the suggested "PROS" on that page.

> If you are unsatisfied with the shape of the 1, I would suggest that you perhaps branch the project and make the modifications needed to satisfy your requirements. I will consider adding an alternate form in a future version of the fonts, but I feel that the current version is acceptable as-is. Thanks for your interest in the fonts.

I'm afraid that's beyond my skills. Just thought it would be a worthy enhancement to be at least mentioned, because why be satisfied with 'good-enough' when you can have it better. If you ever add that mod, I'll be definitely interested. However I understand it's not an easy thing to change without potentially pissing off old users.

None the less, I would like to thank you for this font.

**Comment by pauldhunt** [comment]
My main concern was to distinguish the SCP '1' from other fonts 'l', not within the font.

Usually the design of other fonts is not a typical concern when designing a new/unique font except, perhaps in order to differentiate a new work from what already exists. If I wanted to make SCP like other coding fonts, I would not have made it at all as the whole reason for making the design was to provide a new, different solution that IMO was better than any of the other open source monospaced fonts that were available at the time. 

The 1 is readily recognizable as is the l and they are not easily confused with each other. This is all that should matter to any rational type user. A reader must always find the differences in form by viewing in context. Even your Anonymous example would be ambiguous to some. 

Where you see a defect in the design, I do not. And your complaint is, in fact, the first reported. This leads me to believe that the form of 1 is typically acceptable and that this request boils down to your personal preference, which I find to be at odds with the internally consistent design language of Source Code.

**Comment by Luxsi** [comment]
Ah, well thanks for considering it anyway. I'll believe in your expertise when it comes to fonts, as I know barely anything about designing them. After all what I say is just my personal opinion and not an educated complaint. I do have a mild form of dyslexia and as such value a font that has minimal ambiguity in it.

I don't know where or how I got the impression that SCP was supposed to be the new ultimate best font for programming (might have been me just misreading or interpreting), but with that assumption I figured that even the slightest issue should be considered a flaw. As a programmer I have often multiple documents open, each with a different font, and so I do think that in that case it actually makes sense to take other often used fonts into consideration. But maybe it's just that the 1 sticks out to me annoyingly. For me SCP renders no slope at all on sizes under 11, past that only very small. Changing it to 11 is much better, but takes too much room on the screen.

If I find the time I might try to learn and mod the font slightly to what I would consider to be "perfect".
But if no one agrees with my premise then that settles the argument.

**Comment by pauldhunt** [comment]
@Luxsi I think I will try to slip something in to address this in the next release. I do not plan to alter the default figure `1`, but I will add an alternate accessible via stylistic set. If you then want to set the default to the updated form, you can potentially make the modifications yourself using [Font Squirrel’s webfont generator](https://www.fontsquirrel.com/tools/webfont-generator).

**Comment by Luxsi** [comment]
Sounds good. Thanks!
