### ISSUE TITLE
Missing Metadata on Windows 7+ Control Panel

### ISSUE THREAD

**Issue by be5invis** [adobe-fonts/source-code-pro#129]
I am using official TTF build with digital signature, but the “Designed For”, “Category” and “Manufacturer” field is missing.
![image](https://cloud.githubusercontent.com/assets/240091/15983600/e5d91f7a-2fdf-11e6-8385-4fb5efdf932f.png)

Same problem on adobe-fonts/source-sans-pro#92

**Comment by miguelsousa** [comment]
That metadata comes from a database maintained by Microsoft. Many other fonts are affected. There's nothing we can do to the fonts to address it.

**Comment by be5invis** [comment]
@miguelsousa Any docs to explain this?

**Comment by miguelsousa** [comment]
None public that I know of.

**Comment by DLasher106** [comment]
This is handled by fms_metadata.xml, a hidden file in the C:\Windows\Fonts folder. It's simple enough to add and change entries within it using a text editor. I've added entries for most of my third-party fonts.
