### ISSUE TITLE
Can't compile OTF in releases with UFO

### ISSUE THREAD

**Issue by demcanulty** [adobe-fonts/source-code-pro#131]
Hello, I'm having an issue compiling OTF files in the current master.  I was able to go back to a version from 2014 or so which didn't use UFO files and managed to compile with the `makeotf -r `command, but with the more recent releases I get the following error:

```
Checking that any glyphs in the processed glyphs layer are up to date.
src glyph mturned is newer than processed layer. programName: CheckOutlines
src glyph tturned is newer than processed layer. programName: CheckOutlines
src glyph vturned is newer than processed layer. programName: CheckOutlines
src glyph wturned is newer than processed layer. programName: CheckOutlines
src glyph rturned is newer than processed layer. programName: CheckOutlines
src glyph rsmallinverted is newer than processed layer. programName: CheckOutlines
src glyph interrobangdown is newer than processed layer. programName: CheckOutlines
src glyph universal is newer than processed layer. programName: CheckOutlines
```
I'm able to compile Black and Extra Light, but none of the others.  TTF compiles fine.

**Comment by demcanulty** [comment]
I'm relatively new to this, so it's possible I'm doing something wrong or missing part of the toolchain, I installed the tools fresh from the Adobe FDK download page.

**Comment by frankrolf** [comment]
This error is very familiar – it means that the UFO layers got out of sync.
[Download the latest version of the Adobe FDK](http://www.adobe.com/devnet/opentype/afdko/eula.html), run checkoutlinesUFO and autohint again, and try re-compiling the fonts.

Step-by-step:
```
checkoutlinesUFO -e font.ufo
autohint -q font.ufo
makeotf -r
```

Hope this helps!

**Comment by demcanulty** [comment]
Perfect, thank you!
