### ISSUE TITLE
Source-code-pro doesn't support Chinese?

### ISSUE THREAD

**Issue by JosephusChou** [adobe-fonts/source-code-pro#132]
I installed source-code-pro in my Macbook Air, and chose it as android-studio's default font, however, some Chinese words in my java files became "?????".

**Comment by miguelsousa** [comment]
Did you install the OTF or the TTF fonts? Java does not support OTFs.
And Source Code Pro does not support Chinese. Perhaps you're looking for [Source Han Sans](https://github.com/adobe-fonts/source-han-sans) or [Source Han Code JP](https://github.com/adobe-fonts/source-han-code-jp).

**Comment by JosephusChou** [comment]
thanks @miguelsousa .
