### ISSUE TITLE
Condensed version? (not tall enough)

### ISSUE THREAD

**Issue by jimbo1qaz** [adobe-fonts/source-code-pro#135]
Ubuntu 16.04 x64, Freetype (non-Infinality). TTF font downloaded from Google Fonts using Typecatcher.

Sublime Text x64:

Currently the font is not tall enough. At 9pt, all characters are too short. At 10pt, all characters are a bit wide.

**Comment by pauldhunt** [comment]
This is due to vertical proportions which will not be changed. If you require a font that works for you in the situations described, please 1) use another font 2) design & derive an alternate version of SSP (with a new name) to your required specifications. Best of luck!

**Comment by jimbo1qaz** [comment]
So you will not be adding a semi-condensed variant?

**Comment by pauldhunt** [comment]
Not in the near future. Perhaps longer term.
