### ISSUE TITLE
Digit 1 looks like lowercase L

### ISSUE THREAD

**Issue by gameman15** [adobe-fonts/source-code-pro#136]
I have been trying to transition my team to this font but we all find that your digit 1 looking exactly like courier's letter `l` to be very confusing. Otherwise this font is great!

**Comment by leeoniya** [comment]
it's probably confusing during a transition while both fonts are in use. but really, can any font designer be expected to avoid overlap with a font they're *replacing*?

**Comment by pauldhunt** [comment]
there is an alternate 1 that was added in the last release that can be applied via stylistic sets. alternatively, you could rebuild the fonts to use the alternate 1 as the default. let me know if you need with either solution.

**Comment by gameman15** [comment]
So I opened this up in FontForge and found the alt 1 and replaced the default with it. Thanks for your help

**Comment by gameman15** [comment]
Actually doing this messed up several other characters. I would appreciate help doing this.

**Comment by moyogo** [comment]
@gameman15 Try pyftfeatfreeze from https://github.com/twardoch/fonttools-utils/

**Comment by pauldhunt** [comment]
you may also try Font Squirrel’s webfont generator:
https://www.fontsquirrel.com/tools/webfont-generator

P.S. please remember that modified fonts are not allowed to be redistributed using the Source trademark name, so if you intend to circulate these, you will need to change all instances of the name Source in the modified fonts.

**Comment by gameman15** [comment]
@moyogo Got it to work with pyftfeatfreeze. Thank you!
@pauldhunt I do not plan redistributing that that is a good note, thanks!
