### ISSUE TITLE
Weird vertical alignment of braces / brackets

### ISSUE THREAD

**Issue by Ecco** [adobe-fonts/source-code-pro#137]
The vertical space between brackets and digits is not consistent: the distance between the top of a digit and the top of a bracket is much smaller than the bottom one.
<img width="123" alt="braces_digit" src="https://cloud.githubusercontent.com/assets/55989/17694273/62f19180-63a3-11e6-9f12-2e49cefe2e7d.png">

In the same fashion, braces are not vertically aligned with the "=", "+", "-" symbols:
<img width="169" alt="braces_equal" src="https://cloud.githubusercontent.com/assets/55989/17694181/ec9ed13c-63a2-11e6-9868-e01526ebd4d1.png">

Is that on purpose?

**Comment by pauldhunt** [comment]
the brackets/braces/parens are designed to harmonize with the lowercase as default:
(a) (b) (c) (d) (e) (f) (g) (h) (i) (j) (k) (l) (m) (n) (o) (p) (q) (r) (s) (t) (u) (x) (y) (z)

if there is enough interest, it may be possible to add casing alternates for these in a future version of SCP that harmonize primarily with majuscules.
