### ISSUE TITLE
Link to official font readme file is dead

### ISSUE THREAD

**Issue by bangoker** [adobe-fonts/source-code-pro#138]
The url:

http://www.adobe.com/products/type/font-information/source-code-pro-readme.html

takes to a "Sorry, this page is unavailable" page

**Comment by K-Langoso** [comment]
Indeed. +1

**Comment by kenlunde** [comment]
This appears to be the correct URL:

https://www.adobe.com/products/type/font-information/source-code-pro-readme-file.html
