### ISSUE TITLE
2.030: Coffee emoji not displaying correctly

### ISSUE THREAD

**Issue by martinp** [adobe-fonts/source-code-pro#143]
On version 1.017:
![screen shot 2016-10-08 at 12 38 50](https://cloud.githubusercontent.com/assets/174496/19212578/60d5acbc-8d54-11e6-9210-c2d33f85d3ca.png)

On 2.030:
![screen shot 2016-10-08 at 12 37 42](https://cloud.githubusercontent.com/assets/174496/19212581/6908f3da-8d54-11e6-879a-67498a453933.png)

Screenshot was taken in iTerm2. Has the emoji been removed from the latest version? (2.030)

**Comment by krono** [comment]
I'd say it was added. The first picture shows the 'coffee' from the Apple Color Emoji font.

**Comment by frankrolf** [comment]
What you are seeing on top is fallback to Apple Color Emoji. 
On the bottom (as @krono correctly suggests), is `U+2615 HOT BEVERAGE` as rendered in Source Code Pro.
See the specimen page  for a list of Emoji (and Emoji-like) code points supported in Source Code Pro (♪ ♫ ♥ ​♣​ ♦​ ♠​ ☺​ ☻ ​❤​ ☕​ 💩 ​🤖​ 🔒):
http://adobe-fonts.github.io/source-code-pro/

**Comment by martinp** [comment]
Thanks. Is there a way to build the fonts without the emoji code points?

**Comment by pauldhunt** [comment]
@martinp yes, download the Adobe Font Development Kit for OpenType (here on GitHub). Remove the lines for any glyphs you don’t want in the final font from the Glyph Order and Alias Database file. Rebuild the fonts using the command in the Read Me for this project. Troubleshoot any error messages that may pop up during the process. Good luck!

**Comment by martinp** [comment]
@pauldhunt That did it, thanks!

In case anyone should need step by step instructions:

1. Download the Adobe Font Development Kit from http://www.adobe.com/devnet/opentype/afdko.html and unpack it somewhere (e.g. `~/Downloads`)
2. Clone this repo and checkout the most recent tag: `git checkout 2.030-ro/1.050-it`
3. Remove glyphs from `GlyphOrderAndAliasDB`: `sed -i "" '/coffee/d' GlyphOrderAndAliasDB`
4. Add AFDK to your `PATH`: `export PATH=$PATH:$HOME/Downloads/FDK-25-MAC.b65322/Tools/osx`
5. Follow the instructions from the readme: `cd Roman/Regular && makeotf -r`

**Comment by miguelsousa** [comment]
Removing the lines from the `GlyphOrderAndAliasDB` file will prevent you from being able to build the TrueType fonts, I believe.
Instead, it's better to change the name in the first column. Changing the line from this,
`uni2615	coffee`
to this,
`coffee	coffee`
will preserve the font's glyph order and won't assign the Unicode value to the coffee glyph.

**Comment by martinp** [comment]
@miguelsousa Ok, I've updated my previous comment. Thanks!
