### ISSUE TITLE
Feature request: Bitmap fonts

### ISSUE THREAD

**Issue by DmitryHetman** [adobe-fonts/source-code-pro#155]
Add pre-rendered .psf fonts

**Comment by glennkidd** [comment]
+1 for psf fonts

**Comment by frankrolf** [comment]
Sorry, we haven’t implemented an issue template yet, but requests like this one make it clear that there is a need for one. Please re-word your issue answering the following questions:

>>>

### What exactly is the issue?
[Is this a feature request, a new format, additional styles, language extension, or a bug?
If it involves new file formats or technical suggestions, please link to any documentation, examples etc. you may have.]

### Why am I requesting this feature? Who will benefit from the feature?
[What is the ultimate goal of the addition? Which software/technology will use it? Who are the prospective users? Is this request based on a commercial incentive?]

### How can I help?
[What is your plan to contribute to solving this problem? Do you have a way to contribute time, expertise, or other resources?]

Thank you!

**Comment by pauldhunt** [comment]
unfortunately, this is well beyond the scope of this project. if you require this feature, please branch the project and add the bitmaps you require.
