### ISSUE TITLE
Include Powerline Symbols

### ISSUE THREAD

**Issue by alexanderfahlke** [adobe-fonts/source-code-pro#16]
How about adding the "powerline" symbols to this very nice font?

![powerline.png](https://raw.github.com/alexanderfahlke/issues/master/adobe/Source-Code-Pro/powerline.png)

I know how to patch my fonts manually, but it's a "complex" process for people who just want to start to use this font. I would really like to see these symbols in this font.

Source: https://github.com/Lokaltog/vim-powerline

I use it for some shell-eye-candy:

![shell-eye-candy](https://raw.github.com/alexanderfahlke/issues/master/adobe/Source-Code-Pro/shell-eye-candy.png)

**Comment by pauldhunt** [comment]
Powerline symbols will be in the next release of the fonts, which will likely be sometime in July.
