### ISSUE TITLE
Space Macs Renders Blocks

### ISSUE THREAD

**Issue by Bigotacon** [adobe-fonts/source-code-pro#160]
I have windows 10 and I downloaded a font.ttf file under the Roman/Regular directory and now when I open an application like Spacemacs it renders many rectangles. Please help.

![image](https://cloud.githubusercontent.com/assets/20931755/26288785/724508a6-3e5e-11e7-9714-fb052d711701.png)

**Comment by codeman38** [comment]
The .ttf files in the `master` branch are uncompiled source files. Use the font files from the `release` branch instead.

**Comment by frankrolf** [comment]
Thanks @codeman38! That is the issue indeed.
