### ISSUE TITLE
Please, add Fraktur and Georgian glyphs and cursive italic

### ISSUE THREAD

**Issue by gusbemacbe** [adobe-fonts/source-code-pro#161]
Hello,

* Georgian alphabet: https://www.wikiwand.com/en/Georgian_scripts
* Similar to Fraktur glyphs:
    * Fraktur from Pragmata Pro: https://www.fsd.it/shop/fonts/pragmatapro/#tab-1449666101445-7-7
    * Franktur Unicode: https://www.wikiwand.com/en/Letterlike_Symbols
* Similar to cursive italic: Operator Mono Italic: https://www.typography.com/fonts/operator/webfonts/operatormono-lightitalic/

**Comment by frankrolf** [comment]
Thanks for filing this interesting request – would you mind re-wording your issue answering the following questions:

*What exactly is the issue?*

[Is this a feature request, a new format, additional styles, language extension, or a bug?
If it involves new file formats or technical suggestions, please link to any documentation, examples etc. you may have.]

*Why am I requesting this feature? Who will benefit from the feature?*

[What is the ultimate goal of the addition? Which software/technology will use it? Who are the prospective users? Is this request based on a commercial incentive?]

*How can I help?*

[What is your plan to contribute to solving this problem? Do you have a way to contribute time, expertise, or other resources?]

**Comment by gusbemacbe** [comment]
*What exactly is the issue?*

[Is this a feature request, a new format, additional styles, language
extension, or a bug?

All, except bugs and new format.


If it involves new file formats or technical suggestions, please link to
any documentation, examples etc. you may have.]
The fonts do not have issue. They miss only Georgian letters. I need to
write in Georgian in Atom and other code editors.

*Why am I requesting this feature? Who will benefit from the feature?*

[What is the ultimate goal of the addition? Which software/technology will
use it? Who are the prospective users? Is this request based on a
commercial incentive?]

I and many users want alternative open source cursive monospace glyphs for
an italic font. I use more Fraktur for Maths in Atom. TeX language uses
more Fraktur.

*How can I help?*

[What is your plan to contribute to solving this problem? Do you have a way
to contribute time, expertise, or other resources?]\

As I have said, the fonts do not have problems, but I can give recourses
about how to add Georgian glyphs:

* Open source Georgian fonts:
https://bpgfonts.wordpress.com/category/gpl-gnu/

* Georgian Unicode: https://www.wikiwand.com/en/Georgian_(Unicode_block)

* Open source Fraktur: https://github.com/cyrealtype/UnifracturCook

* Another open source Fraktur font:
https://github.com/mathjax/MathJax/tree/master/fonts/HTML-CSS/Asana-Math/otf
(take Asana Math Fraktur)

* Fraktur Unicode: https://www.w3.org/TR/MathML2/1D5.html

**Comment by gusbemacbe** [comment]
### What exactly is the issue?
The fonts do not have issues. All, except bugs and new format.

### Why am I requesting this feature? Who will benefit from the feature?
I and many users want alternative open source cursive monospace glyphs for an italic font. We discussed about the alternative cursive font for Atom and VSCode:
* https://medium.com/@docodemore/an-alternative-to-operator-mono-font-6e5d040e1c7e
* https://medium.com/@zamamohammed/multiple-fonts-alternative-to-operator-mono-in-vscode-7745b52120a0
* https://github.com/mikaelbr/open-source-ideas/issues/10

I use more Fraktur for Maths in Atom. TeX language uses more Fraktur. 

### How can I help?
As I have said, the fonts do not have problems, but I can give recourses about how to add Georgian glyphs:

* Open source Georgian fonts: https://bpgfonts.wordpress.com/category/gpl-gnu/
* Georgian Unicode: https://www.wikiwand.com/en/Georgian_(Unicode_block)
* Open source Fraktur: https://github.com/cyrealtype/UnifracturCook
* Another open source Fraktur font: https://github.com/mathjax/MathJax/tree/master/fonts/HTML-CSS/Asana-Math/otf (take Asana Math Fraktur)
* Fraktur Unicode: https://www.w3.org/TR/MathML2/1D5.html

**Comment by pauldhunt** [comment]
@gusbemacbe thanks for taking time to answer the questions above. in order to better track your (multiple) requests, please file separate tickets for A) Georgian support B) Fraktur support C) cursive italic. Thanks.
