### ISSUE TITLE
Include character U+1E9E

### ISSUE THREAD

**Issue by newlukai** [adobe-fonts/source-code-pro#162]
Since a couple of weeks, the LATIN CAPITAL LETTER SHARP S is officially part of the German orthography. Would be great if Source Code Pro would include it.

**Comment by frankrolf** [comment]
This glyph is included.

**Comment by frankrolf** [comment]
Please make sure you are using the latest version. The glyph was added in February 2015, which means it made it into the 2.010 release. The current version is at https://github.com/adobe-fonts/source-code-pro/releases/latest

**Comment by newlukai** [comment]
Indeed, it's available. But neither Notepad++ nor WebStorm are able to render it correctly if I enter it via ALT-7838. I need to copy/paste it from Word (where it renders correctly).

**Comment by miguelsousa** [comment]
@newlukai sounds like those apps have bugs.

**Comment by moyogo** [comment]
ALT-7838 is not going to work unless you’ve changed your Windows Registry key `HKEY_Current_User/Control Panel/Input Method/EnableHexNumpad` to 1, and even then it may not work. Before you change that key, the Alt codes are just using the default codepage is on your system, most likely codepage 1252.

**Comment by frankrolf** [comment]
Windows blows my mind. This may help: https://www.johndcook.com/blog/2008/08/17/three-ways-to-enter-unicode-characters-in-windows/
