### ISSUE TITLE
Build script windows

### ISSUE THREAD

**Issue by zePanzerfaust** [adobe-fonts/source-code-pro#163]
Path to python interpreter in Windows build script not found.

With version "AFDKO version 2.5 build 65781 April 3 2017"
and "AFDKO Current Version: 65322 May 27 2016"
(did not take a look at older versions)

On line 13 in build.cmd:
set PYTHON_PATH=%PYTHON_PATH%Python\AFDKOPython\python.exe
should be
set PYTHON_PATH=%PYTHON_PATH%Python\AFDKOPython27\python.exe
AFDKOPython => AFDKOPython27

Without this, addSVGtable.py is not executed.

**Comment by miguelsousa** [comment]
@zePanzerfaust would you care to submit a pull request with that change? That's the fastest route to get things fixed. Thanks

**Comment by zePanzerfaust** [comment]
Ok. I created a pull request.
I also checked the FDK versions, 2.5.64958 and later have this new path.

**Comment by miguelsousa** [comment]
Fixed by #164
