### ISSUE TITLE
1.005 does not validate in Font Book

### ISSUE THREAD

**Issue by opyate** [adobe-fonts/source-code-pro#167]
Please see the screenshot.

<img width="735" alt="screen shot 2017-08-23 at 10 14 31" src="https://user-images.githubusercontent.com/96808/29608418-f5c42988-87eb-11e7-8857-c89e04aa70b4.png">

On OS X El Capitan 10.11.6 (15G1611)

**Comment by opyate** [comment]
Building from source validates and installs perfectly.

**Comment by frankrolf** [comment]
This version of FontBook may not yet know everything about Variable Fonts, and therefore be confused.

**Comment by opyate** [comment]
For the record, the version is: `Version 6.0 (279)`
