### ISSUE TITLE
Add font installation instructions for Linux

### ISSUE THREAD

**Issue by miguelsousa** [adobe-fonts/source-code-pro#17]

**Comment by foozlevazquez** [comment]
Ubuntu 14.04:
```
[ -d /usr/share/fonts/opentype ] || sudo mkdir /usr/share/fonts/opentype
sudo git clone https://github.com/adobe-fonts/source-code-pro.git /usr/share/fonts/opentype/scp
sudo fc-cache -f -v
```

**Comment by yngwin** [comment]
On Gentoo:

    emerge -av source-pro

Set the *cjk* useflag if source-han-sans is also wanted. Set appropriate LINGUAS flags for the regional subsets of Source Han Sans.

**Comment by eksperimental** [comment]
@foozlevazquez i would add this line to the ubuntu instructions:
`sudo rm -rf /usr/share/fonts/opentype/scp/.git*`

**Comment by mykolaj** [comment]
@eksperimental no need to remove git repository, because it allows to download any updates by executing 'git pull'

**Comment by denji** [comment]
```
#!/bin/bash

echo "installing fonts at $PWD to ~/.fonts/"
set -x
mkdir -p ~/.fonts/adobe-fonts/source-code-pro
git clone https://github.com/adobe-fonts/source-code-pro.git ~/.fonts/adobe-fonts/source-code-pro
find ~/.fonts/ -name '*.ttf' -or -name '*.otf' -exec cp \{\} ~/.fonts/ \;
sudo fc-cache -f -v
set +x
echo "finished installing"
```

**Comment by joke2k** [comment]
Maybe we can use `-b master` in order to clone only the master branch instead of all repository.
```bash
git clone -b master https://github.com/adobe-fonts/source-code-pro.git ~/.fonts/adobe-fonts/source-code-pro
```

**Comment by miguelsousa** [comment]
@joke2k You should clone the `release` branch instead, because that's where the OTFs and TTFs are located.

**Comment by rotty3000** [comment]
I used this shortened version of @denji's script:
```
git clone --depth 1 --branch release git@github.com:adobe-fonts/source-code-pro.git ~/.fonts/adobe-fonts/source-code-pro
fc-cache -f -v ~/.fonts/adobe-fonts/source-code-pro
```
HTH

**Comment by mafagafogigante** [comment]
Just in case a Fedora user is reading this, in newer Fedora versions you can use

`sudo yum install adobe-source-code-pro-fonts`

Painless, 1 MB download and installation.

**Comment by divansantana** [comment]
Arch Linux
 sudo pacman -S adobe-source-code-pro-fonts
or
 yaourt adobe-source-code-pro-fonts

**Comment by deb0ch** [comment]
@denji @rotty3000 @foozlevazquez : On ubuntu 16.04 when I tried like you to just clone the repo, put it somewhere fc-cache will look for it (i.e. ~/.local/share/fonts, ~/.local/share/fonts/opentype, /usr/share/fonts or /usr/share/fonts/opentype) and run `fc-cache -f -v`, characters in that font are just displayed as squares (see screenshot).

I believe it is because I did not built the fonts from source (for which I miss the building tools like mkotf).

Seeing your instructions, you seem to have just cloned the repo, ran `fc-cache -f -v` and boom, it automagically worked.

Am I right ? Or what did I miss ?

![screenshot from 2016-06-04 14-26-40](https://cloud.githubusercontent.com/assets/6248219/15799556/e34c1ce6-2a60-11e6-9082-72acef546fc8.png)

**Comment by wiserfirst** [comment]
For Ubuntu 14.04 (based @foozlevazquez's answer, just clone the release branch)

```
[ -d /usr/share/fonts/opentype ] || sudo mkdir /usr/share/fonts/opentype
sudo git clone --depth 1 --branch release https://github.com/adobe-fonts/source-code-pro.git /usr/share/fonts/opentype/scp
sudo fc-cache -f -v
```

**Comment by jickding** [comment]
how to install on freebsd base xface4

**Comment by AbigailBuccaneer** [comment]
This package is available via nixpkgs. To install it and make it available to applications, I did the following:

```
nix-env -i source-code-pro
mkdir -p "$HOME/.config/fontconfig"
cat > "$HOME/.config/fontconfig/fonts.conf << EOF
<?xml version="1.0"?>
<!DOCTYPE fontconfig SYSTEM "fonts.dtd">
<fontconfig>
    <dir>~/.nix-profile/share/fonts</dir>
</fontconfig>
EOF
fc-cache -f -v
```

**Comment by jsejcksn** [comment]
I read that for local usage, `~/.fonts` is now deprecated and that `~/.local/share/fonts` should be used instead. This seems to be confirmed by Font Viewer installing them to that directory in Unity desktop. Is what I read correct?

**Comment by fangqiao** [comment]
I upgraded emacs to 25 then spacemacs can't load Source Code Pro anymore. It worked on emacs 24. 

I use debian the jessie.

**Comment by AbigailBuccaneer** [comment]
@fangqiao see syl20bnr/spacemacs#7696 syl20bnr/spacemacs#7938

**Comment by fangqiao** [comment]
@AbigailBuccaneer  Thanks for the tip. But my problem is not about installing code pro font. I installed it correctly and emacs 24 works well. But the problem is with emacs 25.1, the latest version of emacs. It couldn't find the font.

**Comment by SimonAM** [comment]
@fangqiao I had the same problem. This fixed it:
`sudo apt-get build-dep emacs24`
# If it complains about URI, do this first:
`sudo sed -i -- 's/#deb-src/deb-src/g' /etc/apt/sources.list && sudo sed -i -- 's/# deb-src/deb-src/g' /etc/apt/sources.list`

**Comment by Vdragon** [comment]
There's another issue that I encountered while trying to install Source Han Serif: There's [no simple method](https://unix.stackexchange.com/questions/40480/how-to-unzip-a-multipart-spanned-zip-on-linux) to extract a multipart zip archive files.

**Comment by dpacmittal** [comment]
@foozlevazquez  Your method has a horrible side-effect. For details, please see the bug that I filed with KDE -
 https://bugs.kde.org/show_bug.cgi?id=378227

I would recommend you to edit your comment or removing it altogether.

**Comment by mckennapsean** [comment]
By following @foozlevazquez method of just cloning the repo, any application on linux that uses fonts would take 6s to load (due to scanning for fonts).

For the package maintainers, I scrolled down and found @foozlevazquez 's approach first, hence why I got stuck while trying to install. I love these fonts, and it would be great to point people to using the `release` branch when cloning/downloading. One such approach was posted by @wiserfirst . Thanks!

**Comment by Bost** [comment]
If you compile / build emacs from the source, you need to
```
sudo apt install --yes libgtk2.0-dev
```
and
```
./configure --with-x-toolkit=gtk
```
After years of battling and/or ignoring this issue on and off I found the solution! Hip, Hip, Hurrah!!! Many thanx to:
https://stackoverflow.com/a/18154188 
https://ubuntuforums.org/showthread.php?t=1607632

**Comment by oscarfv** [comment]
@Bost : I build Emacs from source configured with `--with-x-toolkit=lucid` and can use this font just fine. Since I switch fonts often, I defined this convenience command:

```
(defun my-font-source-code-pro (size)
  (interactive "nFont size: ")
  (set-frame-font (format "Source Code Pro\-%d" size) t t))
```
