### ISSUE TITLE
Unable to run regular font on terminal (CMD and Bash on Ubuntu on Windows)

### ISSUE THREAD

**Issue by amankapoor** [adobe-fonts/source-code-pro#171]
I came to know about this font through a reddit link and downloaded the regular version. I installed it on windows and then to run it on my terminal I opened registry editor and moved to Computer\HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Console\TrueTypeFont. Here, I added a new string by the name 000 and set its value to Source Code Pro.

Then, when I changed the font using properties of cmd, it is showing something like this https://imgur.com/a/Lhlrp. Seems like the spaces got no character.

**Comment by miguelsousa** [comment]
Sounds like you may have installed one of the variable fonts. Please try again with the latest non-variable fonts release.
