### ISSUE TITLE
[Request] Cursive italic font support

### ISSUE THREAD

**Issue by gusbemacbe** [adobe-fonts/source-code-pro#176]
## What exactly is the issue?

The fonts do not have issues.

## Is this a feature request, a new format, additional styles, language extension, or a bug?

All, except bugs and new format.

## Why am I requesting this feature? Who will benefit from the feature?

The famous font Operator Mono Pro has a cursive italic typeface, is very loved and wanted by many coders, developers and programmers. But it is very expensive and not all code lovers can afford this. Therefore, we are looking for an open source cursive italic font, then we want a new "Source Code Pro Cursive". 

You can read the discussions:

* https://medium.com/@docodemore/an-alternative-to-operator-mono-font-6e5d040e1c7e
* https://medium.com/@zamamohammed/multiple-fonts-alternative-to-operator-mono-in-vscode-7745b52120a0
* https://github.com/mikaelbr/open-source-ideas/issues/10

## How can I help?

Learn the italic fonts Operator Mono and try to make a cursive italic font in the style of Source Code Pro.

* Similar to cursive italic: Operator Mono Italic: https://www.typography.com/fonts/operator/webfonts/operatormono-lightitalic/

**Comment by pauldhunt** [comment]
So to clarify, are you suggesting that you will create the cursive italic style for Source Code Pro?

**Comment by gusbemacbe** [comment]
Yes, I do, @pauldhunt .

**Comment by pauldhunt** [comment]
Do you need any assistance at this point? If you intend for this to become part of the official Source Code family, our design team would like to be involved in the process.

**Comment by gusbemacbe** [comment]
I am not a professional typodesigner. Sorry!

**Comment by pauldhunt** [comment]
Now i am confused. What are you apologizing for?

**Comment by gusbemacbe** [comment]
I am sorry for misunderstanding my suggestion. You were asking if I suggested that >> **I** << would create.

But I didn't suggest that I would. I suggested that **you and your team** would create. 

I know creating fonts and using Glyphs Mini (I do not have a licence for full Glyphs, I have only for Mini), but I am not professional.

**Comment by frankrolf** [comment]
Why don’t you just buy Operator?

**Comment by gusbemacbe** [comment]
@frankrolf, oh my Force, do you know the price of Operator Mono? There, I can't buy ONE font separated, I have to buy one PACKAGE of styles. One package costs 199 dollars.

Do you think Brazilians are rich and can afford more than 200 dollars to buy the fonts? We can afford only until less than 50 dollars.

And Operator Mono doesn't have Cyrillic, Georgian and Greek glyphs, what is unworthy and a waste of money for me.

**Comment by frankrolf** [comment]
Of course this was a rhetorical question, I know Operator Mono Pro is “expensive”.
No matter what, somebody has to pay the price. What you are realistically asking is for somebody to do free design and development work (not only Latin, but Greek, Cyrillic, and Georgian no less) for at least a year. How expensive is that?
I think the cursive Italic in Operator is not just a novel feature, it is a significant “Alleinstellungsmerkmal”. Andy Clymer (the author of Operator) is a great typeface designer, and I think we should reward him rather than copy his idea.
I cannot speak for Paul here, but I don’t think it makes a lot of sense to incorporate a specific design feature of another typeface into Source Code Pro, which – by the way – does not support Georgian.

**Comment by gusbemacbe** [comment]
> No matter what, somebody has to pay the price. What you are realistically asking is for somebody to do free design and development work (not only Latin, but Greek, Cyrillic, and Georgian no less) for at least a year. How expensive is that?

To get 300 dollars, we, Brazilians, have to keep the money for 6 months for paying the package, so dollar interest and tax in Brazil is higher than euro interest and tax, due to the corruption of our politicians, which deprive us of buying expensive things. 

We do not ask you to make new fonts in less than 30 days. We can wait for your new open source fonts in one, two or three or more years. 

_Andy Clymer (the author of Operator) is a great typeface designer, and I think we should reward him rather than copy his idea._

I didn't say to copy or plagiarise. I say to develop a **cursive font** in the style of Source Code Pro.

>  cannot speak for Paul here, but I don’t think it makes a lot of sense to incorporate a specific design feature of another typeface into Source Code Pro, which – by the way – does not support Georgian.

Where did you learn this nonsense? Did you hear about BPG Fonts, a Georgian typo designers foundry? They made many handwriting, monospaced and sports fonts.

If your font doesn't support Georgian glyphs, it wouldn't support Cyrillic and Greek glyphs. It makes no sense. You wouldn't build the CJK fonts. Glyphs and Glyphs Mini, as FontForge and FontLab, offers the addition of Georgian glyphs. I can write in Georgian in terminal and text editor.

Check the font Ever Mono, it has Armenian, Cherokee, Coptic, Georgian, Hebrew glyphs and many languages, including very old languages:

http://www.evertype.com/emono/

Why do you not invite him?

If you do not want to add or for some reasons, as to please the Russians, I'll study typography to become professional add the glyphs to an open source font by myself and I won't share with you (only if you want to please the Russians). 

As you do not want to build a cursive font and to add Georgian glyphs, I'll close this topic.

**Comment by frankrolf** [comment]
It’s not my intent to upset you, I am sorry if I did. I am trying to explain the problem from our perspective.
I don’t say Source Code Pro couldn’t support Georgian, I am just saying it currently doesn’t. 

Please note that Source Code Pro is not a political project, it is just the best we can do with the resources we have. If there is enough interest for a Georgian addition we may consider it in the future.

**Comment by gusbemacbe** [comment]
> I don’t say Source Code Pro couldn’t support Georgian, I am just saying it currently doesn’t.

Can you explain how it doesn't support Georgian? Are you referring to the cursive or monospaced font?

**Comment by frankrolf** [comment]
Source Code Pro does not contain any characters of the Georgian Unicode Block `U+10A0` to `U+10FF`. 

I am referring to this release: https://github.com/adobe-fonts/source-code-pro/releases/tag/2.030R-ro%2F1.050R-it 
I also think we may be hitting a language barrier here. I am just referring to the current status of the typeface: “does not support” does not mean “will not be able to support”. 
Hope this makes it clearer.

**Comment by gusbemacbe** [comment]
Does "does not support" means "does not contain"?

I, author of Ever Mono and foundry BPG can help you if you want.

**Comment by fitojb** [comment]
@gusbemacbe “[support](http://www.wordreference.com/definition/support)” in English, particularly in the context of software, does not mean the same as “suportar” (‘hold up’) in Portuguese. It’s a very frequent false cognate.

Anyway, asking for whole new blocks of characters to type designers and font engineers is like asking for a unicorn, especially if we’re talking about an open-source project which is not paid for by its users.  It requires collaboration from many people, from designers to coders and quality engineers, as well as testers. All of which should be paid for their time and skills. In GitHub one would expect that the ones asking for something are able to contribute with more than simple words.

> I, author of Ever Mono and foundry BPG

How exactly can they help? Have you asked them or are you funding them? For some reason, I doubt you are in contact with Michael Everson…

**Comment by gusbemacbe** [comment]
> @gusbemacbe “support” in English, particularly in the context of software, does not mean the same as “suportar” (‘hold up’) in Portuguese. It’s a very frequent false cognate.

I understand to support means to be compatible. I misunderstood his comments because I understood he said their fonts family project isn't compatible with Georgian glyphs.

> Anyway, asking for whole new blocks of characters to type designers and font engineers is like asking for a unicorn, especially if we’re talking about an open-source project which is not paid for by its users. 

We would love donating for the support and the continuity of the projects, but you do not have page for donation. 

> It requires collaboration from many people, from designers to coders and quality engineers, as well as testers. All of which should be paid for their time and skills. In GitHub one would expect that the ones asking for something are able to contribute with more than simple words.

I also would love collaborating and contributing, but I am not a professional typo designer yet. I know very well the typography, but not advanced in typography yet. So I am not a quality engineer. I am only a student. I study computer science. And I do not need to be paid. 

> How exactly can they help? Have you asked them or are you funding them? For some reason, I doubt you are in contact with Michael Everson…

I contacted BPG foundry two years old, that if when I finished Georgian an got graduated, I wanted to contribute with them, as adding missed pan-European languages glyphs. So I contacted two Georgians and I'll contact others again.

I didn't contact or know Michael Mono, then we should contact him if he wants to contribute and collaborate.
