### ISSUE TITLE
Windows 10 "is not a valid font file"

### ISSUE THREAD

**Issue by mqudsi** [adobe-fonts/source-code-pro#177]
The latest Source Code Pro release does not appear to work on Windows 10 1709 (build 16299.19). Open attempting to open or import either `SourceCodeVariable-Italic.otf` or `SourceCodeVariable-Roman.otf`, the following message is displayed:

![image](https://user-images.githubusercontent.com/606923/31853444-dff21eae-b64d-11e7-96d4-0aa8deb2f03f.png)

---------------------------
Windows Font Viewer 
---------------------------
The requested file C:\Users\Mahmoud\Downloads\SourceCodeVariable-Roman.otf is not a valid font file. 
---------------------------
OK   
---------------------------

**Comment by miguelsousa** [comment]
Yes, OpenType-CFF2 variable fonts are not widely supported yet.
Install the [latest non-variable builds](https://github.com/adobe-fonts/source-code-pro/releases/tag/2.030R-ro%2F1.050R-it) instead.

**Comment by mqudsi** [comment]
This is the latest pre-release version of Windows 10, per Microsoft, [variable OTF should be supported](https://msdn.microsoft.com/en-us/library/windows/desktop/mt492454(v=vs.85).aspx).

**Comment by miguelsousa** [comment]
@mqudsi that page also spells this out:
> In the Windows 10 Creators Update, DirectWrite does not support variable fonts with CFF outline data using the ‘CFF2’ table.

**Comment by mqudsi** [comment]
Awesome, thanks!
