### ISSUE TITLE
installation in Fontbook on macOS shows ?

### ISSUE THREAD

**Issue by novski** [adobe-fonts/source-code-pro#179]
what i did:
1. download and extract from here: https://github.com/adobe-fonts/source-code-pro/releases/tag/variable-fonts
2. open Fontbook and press + symbol in main Window
3. choose the downloaded folder.
4. i see the source code pro as new font but its subfont shows ?????? in the window where i should see font previews...
what i expected:
to see several subfonts with previews of theyr font as i do with other fonts.
my system: macOS 10.12.6 on a macbook pro 2016
![bildschirmfoto 2017-10-24 um 10 12 40](https://user-images.githubusercontent.com/6088056/31931567-e4cfb960-b8a3-11e7-9eee-3e94abb66005.png)

**Comment by frankrolf** [comment]
see #178 #177

**Comment by miguelsousa** [comment]
@novski Please go back to the download page you used and **READ THE WARNING**. Thank you.

**Comment by novski** [comment]
uff. please excuse...
