### ISSUE TITLE
Clicking "latest release" link currently leads to "variable-fonts" tag

### ISSUE THREAD

**Issue by mgsloan** [adobe-fonts/source-code-pro#180]
The "latest release" link uses this url - https://github.com/adobe-fonts/source-code-pro/releases/latest - which redirects to https://github.com/adobe-fonts/source-code-pro/releases/tag/variable-fonts .  I'm guessing that's not what's intended.  Maybe best just to link to the releases page?  Alternatively, put up with the maintenance of updating the URL in the readme.

**Comment by frankrolf** [comment]
The Variable Fonts release is the latest release, nothing unintentional about that. There is no way of influencing the behavior of the `/latest` URL. 
If you’d like to see other releases, you may click on “all releases” in the README.md file.

**Comment by frankrolf** [comment]
FWIW, there is a link the latest to non-variable release _within_ the description of the latest release.
