### ISSUE TITLE
Rename 'Semibold' as 'SemiBold' (case-sensitive)

### ISSUE THREAD

**Issue by cssobral2013** [adobe-fonts/source-code-pro#182]

**Comment by frankrolf** [comment]
All our font releases follow this naming scheme, so this is unlikely to happen. A workaround for you would be editing the `name` table with a tool like TTX, but please notice you can’t re-distribute modifications using the same family name.

**Comment by cssobral2013** [comment]
Then, I'd want that you explain, why do Google Fonts do have that change (sorry because I can't enter question mark).
