### ISSUE TITLE
V2.030 vs V1.017 rendering comparison

### ISSUE THREAD

**Issue by m4rc1e** [adobe-fonts/source-code-pro#183]
I've just done a quick comparison of the Roman weights between the two versions. Atm, I'm pushing the latest release to Google Fonts since we're still serving v1.017. https://github.com/google/fonts/pull/1381

I've been doing rendering tests at Google Fonts because a lot users do not like changes to x-heights or cap heights, https://github.com/google/roboto/issues/244, https://github.com/google/fonts/issues/644.

This isn't really an issue since you folks probably have your own policy for regressions. I just thought it may be of interest.

[SourceCodePro-v1-vs-v2.zip](https://github.com/adobe-fonts/source-code-pro/files/1532147/SourceCodePro-v1-vs-v2.zip)

I've attached the images since GH compresses gifs badly.

**Comment by miguelsousa** [comment]
Thanks for the data. I browsed thru it and I'm not surprised by the changes, after all you're comparing versions that were released almost 2 years apart.

There's no way for us to validate or provide justification for every single pixel difference. All we can say is that the latest version is what we consider the best.

If there's any particular problem you (or your users can) care to highlight, please open a specific issue.
