### ISSUE TITLE
OpenType-CFF2 format on linux?

### ISSUE THREAD

**Issue by iwconfig** [adobe-fonts/source-code-pro#189]
Is the variable OTF fonts not supported on linux also? Because I cannot get the the variable fonts specifically to work on my system. The other OTF fonts work perfectly.

If thats the case, maybe you should mention that in the latest release as well.

> ⚠️ These .otf fonts CANNOT be installed on Windows or macOS systems because the OSes do not currently support the OpenType-CFF2 format. Install the latest non-variable fonts instead.

**Comment by miguelsousa** [comment]
I don't know what's the status of variable font support on Linux.

@behdad do you know? Or is there no simple answer?

**Comment by behdad** [comment]
With FreeType & Fontconfig of the last year, CFF2 works. Latest GNOME desktop supports variable aspects of variable fonts as well.

https://blogs.gnome.org/mclasen/2017/09/16/fun-with-fonts/
https://blogs.gnome.org/mclasen/2018/01/03/more-fun-with-fonts/

**Comment by iwconfig** [comment]
Oh, i see! I have both FreeType and Fontconfig installed, but not GNOME. Anyway, thanks.

**Comment by bsswartz** [comment]
The variable OTF fonts load and seem to work fine for me in Ubuntu 17.10. Not sure if the variable aspects of the fonts function, but I have used all of the characters commonly used in C. I
