### ISSUE TITLE
Windows charmap/emacs unable to display most of unicode characters

### ISSUE THREAD

**Issue by trippleflux** [adobe-fonts/source-code-pro#190]
I need most of unicode characters to use it on emacs, somehow windows charmap for example unable to display both of U+24D0 & U+24C0, i have installed all of the OTF fonts of souce code pro, but windows charmap or emacs unable to display the unicode chars, mostly it displayed as an character "x" enclosed with a box.

The archive/release that i have downloaded is source-code-pro-2.030R-ro-1.050R-it.zip.

Here is the screenshot : 
![charmap](https://user-images.githubusercontent.com/1216215/36634458-85c40832-19d7-11e8-9c3d-d2c687fc6873.png)

Do source code pro fonts requires any specific windows fonts to be able to use the unicode chars?, strangely U+24D0 & U+24C0 is displayed fine on windows charmap "Segoe UI Symbol" font.

**Comment by frankrolf** [comment]
The Unicode block Enclosed Alphanumerics (U+2460 – U+24FF) is not supported by Source Code Pro.
What you are seeing in the character map is a generic fallback character, which indicates that a particular code point is not supported.

If you are looking for a monospaced typeface that supports a much larger subset of Unicode, have a look at Source Han Code: https://github.com/adobe-fonts/source-han-code-jp
