### ISSUE TITLE
A single place to download fonts

### ISSUE THREAD

**Issue by JKerney-HunterIndustries** [adobe-fonts/source-code-pro#193]
Having to traverse and parse each release that to find the font I want, or even get all the fonts is not user friendly.

It would be highly beneficial to have a single zip that contained all the current released fonts for download.

**Comment by miguelsousa** [comment]
> single zip that contained all the current released fonts for download

https://github.com/adobe-fonts/source-code-pro/releases/tag/2.030R-ro%2F1.050R-it
