### ISSUE TITLE
Android Studio: Windows 10, italic symbols problem

### ISSUE THREAD

**Issue by p-luhin** [adobe-fonts/source-code-pro#199]
Hi all. I've been always using this font, but after moving to windows 10 and installing android studio I faced problems with italic font:

![image](https://user-images.githubusercontent.com/8158004/42315912-372e09f8-8051-11e8-825a-4ff93401a254.png)

As you see, there are two string, the first with regular, ang the second with italic.
BUT: in Intellij IDEA everything is displaying as expected.

What can be the problem?

**Comment by miguelsousa** [comment]
The problem is in Android Studio. Please report the problem to them.
