### ISSUE TITLE
There are some mistake on jdk8_181

### ISSUE THREAD

**Issue by runshinex** [adobe-fonts/source-code-pro#201]
After  on jdk8_141 and netbeans 8.1 , font display very thin when use source-code-pro size 16. But on jdk8_121  and netbeans 8.1 , it's no problem. 
Other font no problem.
OS:win7, netbeans l&f use windows

![menu saveimg savepath20180802105554](https://user-images.githubusercontent.com/5682860/43559906-9e13e11a-95ff-11e8-9538-829a0a7f1d47.jpg)
![menu saveimg savepath20180802105306](https://user-images.githubusercontent.com/5682860/43559907-9e4a0f7e-95ff-11e8-9aff-8167ebc1fc85.jpg)

**Comment by miguelsousa** [comment]
Last time we updated the fonts was more than two years ago, so the differences you're seeing were caused by changes in JDK8. Please report it at https://bugs.openjdk.java.net/projects/JDK/issues/
