### ISSUE TITLE
Hope to support Chinese

### ISSUE THREAD

**Issue by Dragonphy** [adobe-fonts/source-code-pro#202]
As I know, there are lots of Chinese people using this font.Hope to support Chinese.

**Comment by moonlight-iris** [comment]
Basically impossible.
GBK contains 21,003 characters, which makes the bottom line for a "usable" Simplified Chinese font. Considering HK and TW figues ,Japanese Kanji and Kana characters , the number would be even larger.

**Comment by moonlight-iris** [comment]
You can use Noto Han Sans or Wenquanyi fonts for fallback to support CJK characters.

**Comment by moonlight-iris** [comment]
你可以翻翻以前的新闻，看看思源黑体是多少公司合作，用了多长时间做出来的。做CJK字体真的太不容易了。

**Comment by Dragonphy** [comment]
@moonlight-iris 抱歉，没想太多

**Comment by moonlight-iris** [comment]
之前可能语言比较激烈，还请见谅…
建议您可以把思源黑体作为fallback，个人用着感觉不错的。如果在Windows上也可以试试自带的（方正）等线。

**Comment by kenlunde** [comment]
[Source Han Code JP Issue #2](https://github.com/adobe-fonts/source-han-code-jp/issues/2)

**Comment by kenlunde** [comment]
Also → [Source Han Sans vs Source Sans Pro & Source Code Pro](https://blogs.adobe.com/CCJKType/2015/01/shs-vs-ssp-and-scp.html)

**Comment by moonlight-iris** [comment]
@kenlunde 
Wow! So Source-Han-Code could be possible!
Thank you!

**Comment by FloraCanou** [comment]
> Also → [Source Han Sans vs Source Sans Pro & Source Code Pro](https://blogs.adobe.com/CCJKType/2015/01/shs-vs-ssp-and-scp.html)

Oh I almost forgot the OpenType feature. So we can access the monospaced latin glyphs in Source Han Sans by turning on half-width (hwid) & turning off ligatures (liga = 0). 

Example in LibreOffice: type ": hwid & liga=0" right after the font name (without quotes). I have no clue how it works in other apps. Hope this is helpful anyway.
