### ISSUE TITLE
Add more music glyphs

### ISSUE THREAD

**Issue by rettinghaus** [adobe-fonts/source-code-pro#208]
Add glyphs to Musical Symbols Unicode block in range 1D100–1D1FF
see https://www.unicode.org/charts/PDF/U1D100.pdf

**Comment by cjchapman** [comment]
The Noto project includes a music font that may be useful in its own right, and/or as reference material for anyone who is working on adding music glyphs to this (or any other) font.

Here's the Glyphs source for the Noto Music font:
https://github.com/googlei18n/noto-source/tree/master/src/NotoMusic

...and here's a binary version of it, which I believe was compiled by Google's tool chain (as opposed to having been compiled by the Glyphs app):
https://github.com/googlei18n/noto-fonts/blob/master/unhinted/NotoMusic-Regular.ttf

**Comment by kenlunde** [comment]
Thank you, @cjchapman, for providing the _Noto Music_ references, which makes it abundantly clear that adding richer Musical Symbols support to _Source Code Pro_ is an unwise direction.

In addition to the non-monospaced glyphs being an effective non-starter for a typeface whose fonts are intended for editing source code or for use in terminal apps, the additional layout support that is needed to meaningfully typeset such glyphs is baggage that screams "specialized font," which is conveniently exemplified by _Noto Music_.

In my opinion, a separate _Source Music Pro_ typeface would be the better approach.

I'll let someone else close this issue.
