### ISSUE TITLE
Workflow for building TTF Instances from Masters

### ISSUE THREAD

**Issue by i-tu** [adobe-fonts/source-code-pro#212]
Thank you for providing the build.sh script for building release -ready otf and ttf files from the UFO and ttf font instances. It has been a great help in understanding the tooling involved.

I have struggled with constructing a similar script for compiling master UFOs into ttf weight instances (for example `Roman/Instances/Medium/font.ttf`). This prevents me from releasing a ttf font as I’ve understood ttf weight instances a necessary phase for building the release-ready ttf files.

What is used for creating the ttf files in source code pro? Is there some way to do this with free command-line tools, such as afdko or fontmake?

As an aside, when running `makeInstancesUFO -d sourceCodePro.designspace` the generated ufo instances seems to be different to those commited to git. When looking into this, I noticed that the committed instances seem to be behind their master counterparts.

If the instances could be generated automatically from scratch it might be ideal to treat them as temporary build artifacts, and not commit them to git.

**Comment by miguelsousa** [comment]
The **font.ttf** files were made with a process that involved using FontLab. We don't use that process anymore, and thus those files will be removed next time we update Source Code.

Our current process for making the shipping TrueType fonts uses these two tools: **otf2ttf** and **ttfcomponentizer**. Both of these are available in the [afdko package](https://pypi.org/project/afdko/). The `build.sh` script from the [Source Sans repo](https://github.com/adobe-fonts/source-sans-pro/tree/master) will show you how we use them.

> the generated ufo instances seems to be different to those commited to git. When looking into this, I noticed that the committed instances seem to be behind their master counterparts.

Some changes were made to the master UFOs to enable generating variable fonts.

> If the instances could be generated automatically from scratch it might be ideal to treat them as temporary build artifacts, and not commit them to git.

They can, but having a snapshot of the instance UFOs in the repo has greater benefits. They're the source files of the OTF fonts, so they're not quite build artifacts.
