### ISSUE TITLE
Add slashed zero

### ISSUE THREAD

**Issue by cata0309** [adobe-fonts/source-code-pro#214]
Hello, I really like this font family, I use it for programming, but sometimes I really find the dotted zero a little bit confusing.Is there any workaround to bring a slashed zero to the font ? 
Thank you

**Comment by RuixiZhang42** [comment]
The slashed zero is already included in Source Code Pro. You simply need to activate the `zero` OpenType feature:

![zero](https://user-images.githubusercontent.com/39968857/51543981-defc9400-1e2c-11e9-9a35-ebe849e6b12f.png)

**Comment by cata0309** [comment]
How to do that ?

**Comment by RuixiZhang42** [comment]
It depends on whether your editor supports this OpenType feature or not. I&nbsp;suggest that you do a quick search along the lines of `<your editor> OpenType features`.

To quote from https://www.myfonts.com/info/opentype-support-in-applications/:
> [N]ot all operating systems and applications provide access to these features.

This article https://www.macworld.com/article/3052388/software/how-to-access-advanced-opentype-features-in-a-variety-of-mac-apps.html maybe helpful.

**Comment by cata0309** [comment]
And how to activate the slashed zero ?

**Comment by cata0309** [comment]
I use atom editor

**Comment by cata0309** [comment]
If you can help me

**Comment by cata0309** [comment]
I will be very thankful to you

**Comment by RuixiZhang42** [comment]
Again, it depends on your editor. A quick search on the web leads to this comment https://github.com/tonsky/FiraCode/issues/138#issuecomment-187139621 I hope it is helpful and you may consider closing this issue.

**Comment by RuixiZhang42** [comment]
The comment addresses explicitly to the Atom editor. Have you tried that solution?

**Comment by cata0309** [comment]
Can I made the slashed zero point to the right and not left ? I saw that is reversed .

**Comment by ianpan870102** [comment]
I'd also love to see a Slashed-Zero version of Source Code Pro!

**Comment by pauldhunt** [comment]
@cata0309 what do you find confusing about the dotted zero? I’m genuinely curious as to what you mean by this statement.

**Comment by cata0309** [comment]
I used to use sometimes small sizes of light version of the font and the dot was very little and it was hard to distinguish 0 from o, but it isn't a problem from me anymore since I changed my workflow and the font is rendered much cleaner, sorry for late close of this issue, I totally forgot to do it

**Comment by JimEBlevins** [comment]
> How to do that ?

Matthew Butterick's website _Practical Typography_ is an excellent resource, and he has a page devoted to using **OpenType** features. 

[https://practicaltypography.com/opentype-features.html)](https://practicaltypography.com/opentype-features.html)

I note that the free and open-source package **Libre Office** has support for OpenType features in its **Libre Writer:** 
[https://help.libreoffice.org/latest/si/text/shared/01/font_features.html](https://help.libreoffice.org/latest/si/text/shared/01/font_features.html)

I prefer Libre Writer over MS Word for generating PDF files with properly embedded fonts (without needing an expensive Adobe license, in 2022) and for small caps (proper, not emulated).
