### ISSUE TITLE
Source Code Pro cannot be styled in Firefox

### ISSUE THREAD

**Issue by bobthecow** [adobe-fonts/source-code-pro#217]
For some reason, it's not possible to change the color of Source Code Pro in Firefox. It always renders as `#000`. It might be the same problem as #206?

I've reproduced this in Firefox 54 and Firefox Quantum on macOS Mojave. I could _not_ reproduce in either Firefox 54 or Quantum on Windows 10.

This happens with the OTF, TTF, WOFF and WOFF2 versions in the latest build, as well as several older builds I spot checked.

The issue [is visible on the font demo page](https://adobe-fonts.github.io/source-code-pro/). Notice how the "Fork me on GitHub" banner has black text rather than white like in every other browser:

<img width="1018" alt="Screen Shot 2019-03-20 at 3 02 46 PM" src="https://user-images.githubusercontent.com/53660/54722211-39f6f280-4b21-11e9-98d5-61a7b62cd7d3.png">

Also interesting to note is the versions [served by Adobe Fonts](https://fonts.adobe.com/fonts/source-code-pro) and [Google Fonts](https://fonts.google.com/specimen/Source+Code+Pro) _can_ be styled:

<img width="1018" alt="Screen Shot 2019-03-20 at 3 08 14 PM" src="https://user-images.githubusercontent.com/53660/54722613-17190e00-4b22-11e9-994f-5449ddfd46c7.png">

<img width="1018" alt="Screen Shot 2019-03-20 at 3 06 15 PM" src="https://user-images.githubusercontent.com/53660/54722430-b984c180-4b21-11e9-93ec-79f293d536fa.png">

**Comment by miguelsousa** [comment]
Firefox bug https://bugzilla.mozilla.org/show_bug.cgi?id=1520157

**Comment by bobthecow** [comment]
Why do the Google Fonts and Adobe Fonts versions work? Is it because they're being served without the SVG glyphs? 

If so, can we get a build of Source Code Pro without those SVG glyphs to work around the issue? I get that it's a Firefox bug, but web fonts that don't work in Firefox are kind of a deal breaker.

**Comment by miguelsousa** [comment]
> Why do the Google Fonts and Adobe Fonts versions work? Is it because they're being served without the SVG glyphs?

Either that or they're serving an older version.

> can we get a build of Source Code Pro without those SVG glyphs

No, sorry.

**Comment by frankrolf** [comment]
This has been resolved with the latest release (see also #250):
https://github.com/adobe-fonts/source-code-pro/releases/tag/2.032R-ro%2F1.052R-it%2F1.012R-VAR
