### ISSUE TITLE
consider including Degree Celsius and Degree Fahrenheit character

### ISSUE THREAD

**Issue by nerddan** [adobe-fonts/source-code-pro#222]
Please consider including the following characters.

℃ U+2103
℉ U+2109

**Comment by frankrolf** [comment]
I think those symbols might exist in Source Han Code:
https://github.com/adobe-fonts/source-han-code-jp

**Comment by kenlunde** [comment]
@frankrolf Yes, @hatchzo's [_Source Han Code JP_](https://github.com/adobe-fonts/source-han-code-jp) includes glyphs for those two characters, U+2103 ℃ DEGREE CELSIUS and U+2109 ℉ DEGREE FAHRENHEIT, but they are derived from [_Source Han Sans_](https://github.com/adobe-fonts/source-han-sans/) and are full-width (1000-unit horizontal advance). The same is true of [_Source Han Mono_](https://github.com/adobe-fonts/source-han-mono/), which is the Pan-CJK version of _Source Han Code JP_.

In terms of _Source Code Pro_, my personal opinion is that U+00B0 ° DEGREE SIGN followed by C and F (and K, for good measure) is more than sufficient, and is what Unicode intended. The **only** reason why U+2103 ℃ and U+2109 ℉ are in Unicode in the first place is for compatibility with legacy East Asian standards, hence why they are present in the _Source Han_ fonts, and implemented as full-width glyphs. Big Five (Taiwan) and KS X 1001 (South Korea) include both, and JIS X 0208 (Japan) and GB 2312 (China) include U+2103 ℃.

The same can be said of many other characters, an example of which are the upper and lowercase Roman numerals in the [Number Forms](https://www.unicode.org/charts/PDF/U2150.pdf) block.

**Comment by nerddan** [comment]
@kenlunde Maybe we should close this issue?

**Comment by kenlunde** [comment]
@nerddan I don't think that it is a "maybe." 😉

Although I can do so, please go ahead.

**Comment by nerddan** [comment]
Thank you for the detailed illustration!

**Comment by kenlunde** [comment]
My pleasure. 🥃
