### ISSUE TITLE
Cant change color using font-face on Firefox

### ISSUE THREAD

**Issue by andymathieson** [adobe-fonts/source-code-pro#228]
Have fully tested this. The color:green for example shows in Black on Firefox on OSX. Works fine on all other browsers.

**Comment by frankrolf** [comment]
Duplicate of #217

**Comment by frankrolf** [comment]
This has been resolved with the latest release (see also #250):
https://github.com/adobe-fonts/source-code-pro/releases/tag/2.032R-ro%2F1.052R-it%2F1.012R-VAR
