### ISSUE TITLE
Add original Glyphs/Fontlab/etc. project file (for serifs and sans too)

### ISSUE THREAD

**Issue by den32ds** [adobe-fonts/source-code-pro#229]

**Comment by frankrolf** [comment]
The UFO files are the original project files.

**Comment by frankrolf** [comment]
(you may want to have a look in the master branch to find them)

**Comment by den32ds** [comment]
@frankrolf how do you then add new glyphs and modify existing ones?

**Comment by frankrolf** [comment]
I believe all current font editors support UFO source files – in our case we use Robofont:
https://robofont.com
