### ISSUE TITLE
【webstorm2019.3.1】 Garbled characters in the console

### ISSUE THREAD

**Issue by killerddd3** [adobe-fonts/source-code-pro#236]
![image](https://user-images.githubusercontent.com/42941087/74929767-229e4480-5417-11ea-9752-9016170c07da.png)
![image](https://user-images.githubusercontent.com/42941087/74929836-46618a80-5417-11ea-9722-00a6bd47d60d.png)

**Comment by frankrolf** [comment]
Which version and font format are you reporting about?
Please make sure you get the latest release at https://github.com/adobe-fonts/source-code-pro/releases/latest , and test both TTF and OTF formats.
