### ISSUE TITLE
Warning about variable font release

### ISSUE THREAD

**Issue by DLasher106** [adobe-fonts/source-code-pro#241]
The Releases page has the warning:

> ⚠️ These .otf fonts CANNOT be installed on Windows or macOS systems because the OSes do not currently support the OpenType-CFF2 format. Install the latest non-variable fonts instead.

This may be misleading, and should be reworded to say that Windows 10 _can_ use the _.ttf_ variable fonts.

**Comment by frankrolf** [comment]
Re-wording needs to happen since macOS 10.15 supports CFF2 .otf files, but I wonder what’s misleading about the rest?
The last sentence, perhaps?

**Comment by BornForFever** [comment]
Well, I once installed the otf and ttf variable font and they both worked well on my windows10.

**Comment by frankrolf** [comment]
Installing both formats in parallel is not recommended, since the internal font names are the same across formats. In the best case you won’t know which font format you are dealing with, in the worst case there will be crashes.

**Comment by frankrolf** [comment]
“Worked fine” also is relative – the CFF2 file may work when placed in the InDesign fonts folder (for example), or used through Chrome – but it doesn’t mean that the OS supports the format natively.

**Comment by BornForFever** [comment]
I'm sorry I didn't make it clear. In fact, I installed the otf variable font, and then uninstalled it, and then installed the ttf font.

**Comment by frankrolf** [comment]
Thanks! I will do some investigation on my end, and update the note accordingly.

**Comment by ValZapod** [comment]
variable otf works in windows 10 20H2, LOL. Not only that, but you can even open the properties of the variable font in modern Settings app (as opposed to Control panel)! So it is false, I am of course not so sure you can use those in non UWP apps... But whatever. Word does not work for example.

**Comment by ValZapod** [comment]
> in the worst case there will be crashes

I doubt that. If there is it is a bug in Windows.

**Comment by pauldhunt** [comment]
I have removed all these warnings as it seems the latest versions of Mac and Windows operating systems includes VF font support.
