### ISSUE TITLE
Some block characters not 100% width

### ISSUE THREAD

**Issue by lighth7015** [adobe-fonts/source-code-pro#242]
On linux, when using TUI applications, Source Code Pro has some SLIGHT space between the box shadow glyphs.
![image](https://user-images.githubusercontent.com/671336/80381904-9e7d9880-886f-11ea-9529-5d7769bfb669.png)

**Comment by frankrolf** [comment]
That’s an odd one – I’d be surprised if `  Quit  ` uses a different box than the shade (and FWIW, the shade of the window itself). Is if possible for you to paste what we’re seeing as characters here?

**Comment by lighth7015** [comment]
The author of the library gave me an example to paste in my terminal, and I can confirm the issue is with the glyph itself, though here is the character it is writing to the terminal- 
```
echo -e "\u2580\u2580\u2580"
```

**Comment by lighth7015** [comment]
Here is a Konsole screenshot, with the line hilghighted, so the edges of the character can be seen.
![image](https://user-images.githubusercontent.com/671336/80424688-3bf8bc80-88b0-11ea-9f89-949e111eefea.png)

**Comment by frankrolf** [comment]
As far as I can see, the glyph itself is 600 units (a.k.a. 100%) wide in all the instances. See for example. here: https://github.com/adobe-fonts/source-code-pro/blob/master/Roman/Instances/Regular/font.ufo/glyphs/uphalfblock.glif

This is an issue that has to do with the rasterizer used. Have you tried to see what happens if you are using the alternate outline format? (TTF if you’re currently using OTF, and vice-versa).

**Comment by lighth7015** [comment]
Installing the ttf versions of the fonts, and will reply in a few minutes! :D

**Comment by lighth7015** [comment]
Yeah, apologies. Konsole is has issues with Source Code Pro, it seems!

**Comment by frankrolf** [comment]
That’s too bad! What happened when using the TTFs? Also, which fonts work well for you?

**Comment by lighth7015** [comment]
The TrueType variants also exhibit the 1px space to the right of the block glyphs. I mean I love Source Sans and Source Code, they're amazing fonts! But I'm just trying to track down where this is coming from so it can get fixed. :D

**Comment by lighth7015** [comment]
I figured it out; somehow KDE's anti-aliasing is adding that spacing between the characters. :D

**Comment by lighth7015** [comment]
Specifically, "Font smoothing" was the culprit. :D

**Comment by lighth7015** [comment]
Yeah, it's been a little over a week and I'm not seeing that issue anymore with my workaround. So I feel safe closing this. Thanks so much for the assistance figuring out what's going on! :D
