### ISSUE TITLE
adobe-fonts.github.io color issues

### ISSUE THREAD

**Issue by 532910** [adobe-fonts/source-code-pro#244]
https://adobe-fonts.github.io/source-sans-pro/, https://adobe-fonts.github.io/source-serif-pro/ and https://adobe-fonts.github.io/source-code-pro/ doesn't redefine colors, so all of them look fine in the dark browsers:

![image](https://user-images.githubusercontent.com/14617699/80920356-03595700-8d78-11ea-8255-5d0a1b110bf2.png)

But when mouse is over, all are completely unreadable:
![image](https://user-images.githubusercontent.com/14617699/80920357-05231a80-8d78-11ea-9081-7e608feba7f0.png)

You should define both foreground and background colors together, implicitly, or not define them at all. Really you shouldn't reproduce it (just define both fg and bg and don't rely on common defaults), but if you want, it is firefox with browser.display.use_system_colors = true and env GTK_THEME=Adwaita:dark

**Comment by pauldhunt** [comment]
can you update the source and submit a pull request? or provide the code necessary for me to plug into it? thanks.

**Comment by 532910** [comment]
1. I don't see web page source in this repo.

2. The issue is here:
```
div:hover
{
    background-color: #EEE;
}
```

**Comment by frankrolf** [comment]
I am currently fixing this problem for the Source Serif specimen page, but I could not get a dark background to appear, even when setting dark mode globally.
The solution would be setting the colors explicitly, like this:

```

        @media (prefers-color-scheme: dark) {
            body {
                background-color: #222;
                color: #FFF;
            }
            div:hover
            {
                background-color: #333;
            }
        }
        @media (prefers-color-scheme: light) {
            body {
                background-color: #FFF;
                color: #000;
            }
            div:hover
            {
                background-color: #EEE;
            }
        }

```

This keeps the current hover color intact for light themes, and redefines background-, font-, and hover colors in dark mode.
The grey for the `h2` can stay as-is IMO.

<img width="1280" alt="Screen Shot 2020-11-05 at 10 02 19" src="https://user-images.githubusercontent.com/2049645/98220072-1975e900-1f4e-11eb-94ae-829c9d579339.png">
<img width="1280" alt="Screen Shot 2020-11-05 at 10 02 34" src="https://user-images.githubusercontent.com/2049645/98220080-1b3fac80-1f4e-11eb-88c5-f2e476df2481.png">

**Comment by 532910** [comment]
> could not get a dark background to appear

did you set `browser.display.use_system_colors = true` and restarted firefox?

**Comment by frankrolf** [comment]
I did not, and even when I do – it does not change a thing (except darkening the text on the ribbon). So I take it that it’s safer to just specify the color directly.
<img width="887" alt="Screen Shot 2020-11-05 at 16 29 53" src="https://user-images.githubusercontent.com/2049645/98260910-29102480-1f84-11eb-925b-de416b039ec9.png">

**Comment by 532910** [comment]
Still not fixed.

**Comment by frankrolf** [comment]
You’ll find out here as soon as it is!

**Comment by pauldhunt** [comment]
@532910 can you confirm the issue is now resolved? thanks.

**Comment by 532910** [comment]
Only for sans and code. Serif still looks the same.

**Comment by frankrolf** [comment]
The specimen for Source Serif will change completely in the next few weeks, so I did decide not to update the old CSS there.
Thanks for pointing out the issue!

**Comment by 532910** [comment]
Thank you for resolving!
