### ISSUE TITLE
Details of available Stylistic Sets

### ISSUE THREAD

**Issue by krish-r** [adobe-fonts/source-code-pro#246]
Hi, 
First of all, thanks for this awesome font. 
While playing around with vs code font ligatures option, I was able to activate some of the stylistic sets (ss02, ss03, etc.). 
But somehow I could not find details of the available stylistic sets in the repository/readme. 
Can someone please point me to that documentation/help me with the details of available stylistic sets.
Thanks.

**Comment by frankrolf** [comment]
You are right – there is little documentation about those!
Two workarounds:
- some applications can read the names of stylistic sets, such as Adobe Illustrator, InDesign and Photoshop. You will see those names in the OpenType menu.
- you could check the source files for OpenType features and find the contained names, e.g. here: https://github.com/adobe-fonts/source-code-pro/blob/01b97528a2c65621d79eb1795323e9a7f7612f10/Roman/familyGSUB.fea#L644

None of those solutions provides an “at a glance” overview though, so this is something for the to-do list.

Hope the workarounds at least help a little.

**Comment by krish-r** [comment]
Thanks, this surely helps. :)

Tried to pull the headers & description from the source file for my reference. 
Adding few of them here for quick reference, hope this might be useful for others too. 

| Stylistic Sets | Description |
| ----- | ----- |
| ss01 | Typographic alternates |
| ss02 | Alternate a, cursive beta |
| ss03 | Alternate g, cursive theta, Serbian be |
| ss04 | Alternate i |
| ss05 | Alternate Sami uppercase Eng, cursive phi |
| ss06 | Alternate dollar sign |
| ss07 | Alternate numeral one |
| zero | Slashed Zero |
| salt | Stylistic Alternates - Applied |

| Character Variants | Description |
| ----- | ----- |
| cv01 | Alternate lowercase a |
| cv02 | Alternate lowercase g |
| cv04 | Alternate lowercase i |
| cv06 | Sami uppercase Eng |
| cv07 | Cursive beta |
| cv08 | Cursive theta |
| cv09 | Cursive phi |
| cv10 | Serbian be |
| cv11 | Cyrillic breve |
| cv12 | Slashed zero |
| cv14 | Typographic hyphen |
| cv15 | Typographic asterisk |
| cv16 | Barred dollar sign |
| cv17 | Alternate numeral one |
