### ISSUE TITLE
请问可以实现中文英文宽度1:2吗？

### ISSUE THREAD

**Issue by jerviscui** [adobe-fonts/source-code-pro#251]
您好，请问字体可以实现一个中文跨度对齐两个英文宽度吗？
如果不能支持的话，请问有什么建议么？比如我自己可以动手操作的。

还是喜欢 source-code-pro 的英文效果。

**Comment by frankrolf** [comment]
Maybe you are looking for https://github.com/adobe-fonts/source-han-code-jp ?

**Comment by jerviscui** [comment]
Thank you. 
But the font is not also 2:1.
![image](https://user-images.githubusercontent.com/6396748/97515923-0783cb80-19cd-11eb-9b3d-d59e4fb05a32.png)

**Comment by RuixiZhang42** [comment]
@frankrolf Either [Source Han Code JP](https://github.com/adobe-fonts/source-han-code-jp) or [Source Han Mono](https://github.com/adobe-fonts/source-han-mono) has non-CJK glyphs being 667-unit wide. So 3 Latin letters occupy approximately the same horizontal space as 2 CJK ideographs.

@jerviscui A 1:2 ratio is asking for non-CJK glyphs to be 500-unit wide, which is a very “condensed” style (some would say it’s already “compressed”). The result is that wide letters (such as `M`, `m`, `W` and `w`) will *not* look good (to native speakers of Latin-based languages). Maybe you can try [M+ FONTS](https://mplus-fonts.osdn.jp/). The 3 families M<sup>+</sup> M Type-1, M<sup>+</sup> M Type-2 and M<sup>+</sup> MN Type-1 all feature Latin fixed-halfwidth characters.

**Comment by jerviscui** [comment]
@RuixiZhang42 
Thank you let me know why.
Yes，500-unit wide is not friendly for read.  Source Code Pro letter spacing is comfortable.

I'm using Inconsolata now. But I think Inconsolata letter spacing is a little bit less than Source Code Pro.

**Comment by frankrolf** [comment]
Thanks @RuixiZhang42.
I’ll close this now, feel free to reopen if necessary.
