### ISSUE TITLE
error using ttx with variable font

### ISSUE THREAD

**Issue by zePanzerfaust** [adobe-fonts/source-code-pro#258]
Hello,

I downloaded VAR-source-code-var-1.012 to make changes as discussed in
- https://github.com/adobe-fonts/source-code-pro/issues/157#issuecomment-317263987
- https://github.com/adobe-fonts/source-code-pro/issues/157#issuecomment-317717059

This used to work but now ttx gives me an error
`ERROR: Unknown file type: "SourceCodeVariable-Italic.otf"`
when executing
`ttx -t cmap SourceCodeVariable-Italic.otf` or just `ttx SourceCodeVariable-Italic.otf`

`ttx --version`
`4.18.2`

The OTF and TTF versions worked fine.

Now the question is, should it work?
If not, is there an alternative?

**Comment by zePanzerfaust** [comment]
The problem that lead to the issue, was that the merge of the font failed. This corrupted the file and therefore ttx no longer recognizes it.
The reason it failed in the first place are the missing alternative glyphs. Are they no longer available in the variable font?
For example "asterisk.a"?

**Comment by punchcutter** [comment]
@zePanzerfaust The alternate asterisk glyph in the variable OTF is named `glyph00705` so if you replace `asterisk` with that in the dumped cmap and then merge with `ttx -m SourceCodeVariable-Italic.otf SourceCodeVariable-Italic.ttx` (or whatever the name of the dumped ttx file is) then it should work. I tried it here and it worked for me. If you have a problem like mentioned above `ERROR: Unknown file type: "SourceCodeVariable-Italic.otf"` then that means there's something wrong with the font so you should download it again from here and try again.

**Comment by zePanzerfaust** [comment]
This replaces the asterisk by the tilde or official Unicde name "Greek Perispomeni"?
By generating the complete ttx output an entry "<GlyphID id="705" name="uni1FC0"/>" can be found.
So the mentioned glyph00705 references uni1FC0, which I assume is the Unicode hex value of "Greek Perispomeni"? That's just my assumption and it seems to make sense.
Now my question would be, what is the alternative asterisk name and how to find it? Do you use a visual tool to look them up?
For this I dumped the Roman version of the font.

**Comment by zePanzerfaust** [comment]
Thank you! This pointed me in the right direction. Dumping the whole font file with ttx and searching for `asterisk` gives several matches. The ones in the cmap and then there is
```
        <!-- SubTableCount=1 -->
        <SingleSubst index="0" Format="1">
          <Substitution in="asterisk" out="glyph01001"/>
        </SingleSubst>
```
which is the alternative version I was looking for. Then following what you said, replacing `asterisk` with `glyph01001` in the cmap and merging the font.

**Comment by zePanzerfaust** [comment]
Beware that the glyph ID in the Roman and Italic versions are not the same!
In case of the asterisk it is the following.
Roman: `glyph01001`
Italic: `glyph00705`
