### ISSUE TITLE
Please release new version to NPM

### ISSUE THREAD

**Issue by andersk** [adobe-fonts/source-code-pro#272]
The current version of [`source-code-pro` on NPM](https://www.npmjs.com/package/source-code-pro) is 2 years old and triggers an important bug on macOS (#217, #250). I’ve verified that the version in Git is unaffected. Could you please upload the new version to NPM?

**Comment by pauldhunt** [comment]
@andersk is there anyone at the NPM community that can do this work?

**Comment by andersk** [comment]
NPM lists the package collaborators as [msousa](https://www.npmjs.com/~msousa) (@miguelsousa?) and [frankrolf](https://www.npmjs.com/~frankrolf) (@frankrolf?). I believe anyone else would need to be invited by one of them.

**Comment by frankrolf** [comment]
https://www.npmjs.com/package/source-code-pro
