### ISSUE TITLE
f and other slim characters get merged

### ISSUE THREAD

**Issue by lever1209** [adobe-fonts/source-code-pro#290]
fi, fl, and ff all get merged into one character instead of true monospace

**Comment by pauldhunt** [comment]
Hi can you tell me on what operating system, and program you are noticing this behavior? Additionally, can you provide a screenshot of what you are viewing? Based on the code within the font, this is not programmed to happen as there is no `liga` (ligature) feature currently implemented. However, there are ligature glyphs in the font to support Unicode points. If your application is doing this by default then the problem resides there and not with the font programming. Please do a bit more testing so we can determine whether this is a font or application issue. Thanks.

**Comment by lever1209** [comment]
~~any application under archlinux, including but not limited to eclipse ide, discord, and firefox~~

after double checking all the spots i can remember, it seems to have been patched
