### ISSUE TITLE
GitHub Pages site unavailable

### ISSUE THREAD

**Issue by EliahKagan** [adobe-fonts/source-code-pro#305]
Following the [Source Code Pro](http://adobe-fonts.github.io/source-code-pro/) link in [`README.md`](https://github.com/adobe-fonts/source-code-pro/blob/release/README.md) goes to a 404 page.

I don't believe this problem is related in any way to my internet connection, because I was [informed](https://github.com/EliahKagan/weighted-intervals/actions/runs/3972669617) of it by a GitHub Action (so it was inaccessible from a cloud machine, too), and because [Down for Everyone or Just Me](https://downforeveryoneorjustme.com/adobe-fonts.github.io?proto=http) also shows it as down.

[There was a deployment](https://github.com/adobe-fonts/source-code-pro/deployments) to GitHub Pages about eight hours ago, but I don't know if that is related to the breakage. The deployment appeared to succeed.

**Comment by punchcutter** [comment]
Thanks for the report. Fixed!
