### ISSUE TITLE
1.024: Upright and Italic variable fonts have different family names

### ISSUE THREAD

**Issue by codeman38** [adobe-fonts/source-code-pro#309]
In the latest version of the variable fonts (1.024), the upright font has the family name `SourceCodeVF` (no spaces), while the italic font has the family name `Source Code VF` (with spaces). This prevents style linking between the upright and italic fonts.

**Comment by pauldhunt** [comment]
well that’s embarrassing. will try to patch ASAP.

**Comment by pauldhunt** [comment]
This should be fixed in the [latest release](https://github.com/adobe-fonts/source-code-pro/releases/tag/2.042R-u%2F1.062R-i%2F1.026R-vf).
