### ISSUE TITLE
Should slashed zero lean in the opposite direction?

### ISSUE THREAD

**Issue by wincent** [adobe-fonts/source-code-pro#336]
Splitting off a new issue in relation to [this comment](https://github.com/adobe-fonts/source-code-pro/issues/214#issuecomment-456683540).

Looking at [this list of monospace programming fonts](https://hackingcpp.com/dev/coding_fonts.html) and clicking on "Distinct Zero", I see 30 fonts where the slash starts in the bottom left and extends towards to top right (ie. like `/`). But I only see 1 font (Luculent) where it starts in the top left and goes down towards the bottom right (ie. `\`).

So, Source Code Pro is in a distinct minority there — having a slash that goes like `\` — which makes the slashed zero look decidely odd. Any chance that we might flip it in the opposite direction?

**Comment by frankrolf** [comment]
(commenting as an observer, not as the designer)

The sole intention of a slashed/dotted 0 is to make it distinct from the O in a string like `0O0O0`.
Some designers want to make their slashed 0 be distinct from the Ø as well, hence the top-left to bottom-right slash. `0Ø0Ø0`

**Comment by AbraxasDMG** [comment]
Hi. Could an "vertically mirrored" slashed zero `0` be introduced as a character variant?
Thanks!

**Comment by pauldhunt** [comment]
I’m sorry, but I’m not inclined (pardon the pun) to include another alternate zero in the font for this purpose.

**Comment by wincent** [comment]
FWIW, I wasn't suggesting an alternate be added, but that the existing one be changed.

**Comment by AbraxasDMG** [comment]
Could someone help with creation of the zero upright and italic glyphs with the slash in the opposite direction? It would be highly appreciated. These don't have to be included in the official repository or the released font itself. We could keep them in a separate repository as a drop-in replacement, similar to what Hack font team did (https://github.com/source-foundry/alt-hack), or do anything else that the team here finds more appropriate.

Renaming the font (to respect the reserved name of the original font) and building the font from source by the end-users wouldn't be a problem. The only issue is that redesigning the zero glyph requires a certain level of design and technical proves, which is probably not available in abundance around, but the team here already posses.

**Comment by wincent** [comment]
Funnily enough, I was just playing with [CodingFont](https://www.codingfont.com/) and discovered that one of the fonts, [Anonymous Pro](https://www.marksimonson.com/fonts/view/anonymous-pro/), had a similar situation:

> In the earlier fonts, the slashed zero, designed to look different than the capital "O", goes the "wrong" way compared to most fonts that have this feature. Susan and David did this intentionally to distinguish it from the slashed capital "Ø" used in some languages. Some people thought this looked odd, so I put it the "right" way, and distinguish it from the "Ø" by keeping the slash inside the character.
