### ISSUE TITLE
Powerline symbols

### ISSUE THREAD

**Issue by amadeus** [adobe-fonts/source-code-pro#43]
Understandably I am in the minority with this issue, but I figured I would post it here to get your thoughts.

I use Source Code Pro in MacVim, but more importantly I use with a special plugin called Powerline that has support for some custom glyphs that provide an overall nicer user experience.

The Powerline project includes a font patching tool to add these glyphs manually, however it has some issues when placing them, as can be seen by the screenshot below:

![bug-tweak](https://f.cloud.github.com/assets/83376/20570/770d9158-495a-11e2-9fdd-a792e6442ec4.png)

Notice how the arrows and Line Number glyphs seem to get chopped off at the bottom due to their vertical alignment being a tad lower than what should be expected?

Since I don't know much about font development, here's a link by the project author that explains the issue.

https://github.com/Lokaltog/powerline/issues/14#issuecomment-11506848

Sounds like the potential fixes either include some custom hackery with the font patcher to fix the glyph alignment or a potential fix in Source Code Pro itself, however it could also be the reason for it not working could be an intentional design piece on your own. He also mentioned potentially submitting a patch that includes the glyphs built in, however I am not sure whether you guys would even be open to that in the first place.

**Comment by sharktamer** [comment]
I've checked out that branch, built the fonts, but I'm not seeing the symbols. Is there something I'm missing?

**Comment by whitneyit** [comment]
I see the custom sauce symbols but not additional Unicode characters like
http://www.fileformat.info/info/unicode/char/25B6/index.htm

**Comment by miguelsousa** [comment]
@whitneyit [a few comments above](https://github.com/adobe-fonts/source-code-pro/issues/43#issuecomment-57718556) @pauldhunt asked if it was just 7 glyphs. So is it not?

**Comment by whitneyit** [comment]
It seems that several Unicode characters are not showing. For example, the
special nerdtree folder icons don't work either

**Comment by whitneyit** [comment]
I can attach a screen shot when I get home

**Comment by whitneyit** [comment]
Consolas
![Consolas](http://i.imgur.com/XNw8cj9.png)

Sauce Code
![Sauce](http://i.imgur.com/LRLZV7u.png)

Notice the folder icons, ▾ in nerdtree and the ▸ character is not being displayed correctly

**Comment by miguelsousa** [comment]
Those two characters — U+25BE, U+25B8 — have nothing to do with Powerline support. This is the [list of Powerline characters](https://github.com/Lokaltog/vim-powerline/blob/develop/fontpatcher/README.rst#glyph-table).

Open a new issue if you'd like to request support for those two characters.

**Comment by gbitzes** [comment]
It appears that the powerline arrows introduced in pauldhunt/SourceCodePro are not big enough to create the smooth, continuous effect we are aiming for:

![wrong-powerline](https://cloud.githubusercontent.com/assets/3705326/7163807/ac011466-e3a4-11e4-91ac-7a1ce4d278d8.png)

This is how it looks like when using the "Sauce Code Pro" font:
![correct-powerline](https://cloud.githubusercontent.com/assets/3705326/7163817/be43a44a-e3a4-11e4-88e5-588ce98018a3.png)

The difference in thickness is also visible in fontforge, in which the arrows extend to the top of the character border - new symbols:
![fontforge-new](https://cloud.githubusercontent.com/assets/3705326/7163916/6a499d12-e3a5-11e4-9652-71ca7936b4b5.png)

Patched font:
![fontforge-patched](https://cloud.githubusercontent.com/assets/3705326/7163918/6eacf296-e3a5-11e4-9d60-8f8a082a377e.png)

(The new font depicted above comes from compiling b086f07a6cb5f6f1680fdfc2308b7f92d6c3e59b)

**Comment by pauldhunt** [comment]
This is good to know. Are there any design guidelines for these characters?

**Comment by Lokaltog** [comment]
Not really, the arrow glyphs have to be manually adjusted and tested to see if they work, and not every setup displays them correctly. Fixing the issue on one setup may end up creating another issue on other setups. I think it's impossible to get a consistent look across all setups, e.g. if you increase the glyph size to fix the antialiasing issue displayed above (the gap between the glyphs), you'll notice that the arrows end up clipped and slightly misaligned instead.

I guess you could try to make the glyphs slightly taller, just enough to close the gap and avoid the clipping, but note that if you resize the glyphs outside the font's bounding box other terminal emulators may end up either drawing the glyphs outside the bounding box (which looks even worse), or scaling the entire font to fit the size of the arrow glyphs, messing up the leading or tracking of the rest of the font.

I apologize if this is a stupid question, but could a possible solution to this issue be to add hinting to the glyphs so they line up properly? Or maybe add kerning information that moves the glyph ever so slightly to the left to close the gap?

**Comment by pauldhunt** [comment]
for now i just extended the large edge of the big, black triangles to meet the edge of the bounding box (to the left and right), the previous version had a 20 unit gap (which is what is probably causing the blue gap). I’ll look at Sauce for other proportions.

**Comment by pauldhunt** [comment]
The next release of the family is imminent and will include these characters, so I am closing this one for now.

**Comment by pauldhunt** [comment]
Resolved in the latest release:
https://github.com/adobe-fonts/source-code-pro/releases/tag/2.010R-ro/1.030R-it

**Comment by amadeus** [comment]
@pauldhunt This release works great! Thanks so much! Three years in the making!

**Comment by beanaroo** [comment]
Not sure if this is worth mentioning, but I too experience the blue line issue displayed by gbitzes in vte terminals and xterm. 

Using Sauce Code Pro is a workaround.

**Comment by pauldhunt** [comment]
@beanaroo which version of the fonts are you using?

**Comment by beanaroo** [comment]
@pauldhunt I am using the latest release, 2.010R-ro/1.030R-it. 
I have noticed other reports of the same behaviour for tmux/zsh/vim plugins but can't be certain which ones are relevant.

**Comment by pauldhunt** [comment]
@beanaroo can you post some screenshots of how things are displayed in your working environment? That would help me to troubleshoot things. Thanks.

**Comment by beanaroo** [comment]
Sure thing. In the screenshot below, the two terminals on the left are using the Adobe version and the two terminals on the right are using the powerline patched version, [Sauce Code Pro](https://github.com/powerline/fonts/tree/master/SourceCodePro). All other glyphs are a fall back font, ttf-font-awesome. I tested the [nerd-fonts](https://github.com/ryanoasis/nerd-fonts) version too, but seeing as it leaves Adobe's powerline glyphs untouched, there is no noticable difference.

![screen_adobe_powerline](https://cloud.githubusercontent.com/assets/1748909/13456027/cd94d968-e0c5-11e5-87d9-143fd19470b0.png)

**Comment by pauldhunt** [comment]
I’ll take another stab at this next time we update the fonts.

**Comment by austincrft** [comment]
@beanaroo: This probably isn't the place for this, but I'm super curious. What desktop environment are you using? It looks great.

**Comment by beanaroo** [comment]
@austincrft Just for you:  :page_with_curl: [dotfiles](https://github.com/beanaroo/dotfiles)
Oh, and I believe it's the font that makes it look so great!

**Comment by JoelOtter** [comment]
Hi all,

Latest version of the fonts (2.030), and my arrows are _very_ slightly vertically misaligned. Hopefully it can be seen in these snippets:

![](https://cloud.githubusercontent.com/assets/2765356/17214576/8791a9f2-54d1-11e6-93d6-420e194ebbdb.png)
![](https://cloud.githubusercontent.com/assets/2765356/17214577/8792bb30-54d1-11e6-8117-0da1f058213c.png)

It looks like the arrows are either slightly too large, or placed slightly too high. I don't know a great deal about fonts so I'm not precisely sure what could be causing this issue, but I thought this was probably the best place to start.

These are from tmuxline, but the error happens in vim-airline too, so I think it's the font. I'm using iTerm 3 with all fonts set to SCP 12pt. If I shrink the non-ASCII font to 11pt, they seem to align vertically, but I now see the gap others have described.

Cheers!

**Comment by kenlunde** [comment]
@pauldhunt In case you were not aware, @be5invis submitted [L2/19-068](https://www.unicode.org/L2/L2019/19068-powerline-syms.pdf) that is a proposal to encode the Powerline symbols, which will be discussed during UTC159 that starts on the last day of this month. If accepted, and once they are included in a version of Unicode, you will be able to change the mappings from PUA code points to non-PUA ones.
