### ISSUE TITLE
"Fonts Only" download link

### ISSUE THREAD

**Issue by brubrant** [adobe-fonts/source-code-pro#52]
Hi,

Thanks for sharing this great work!

I suggest you update de Readme.md to include a link to a place where people can downlod only the fonts. I think most of who comes to the Repo's Page wants only **to use** your beautiful fonts.

I saw you used to upload it to Github before they discuntinue this option. The best option to download I found is: http://sourceforge.net/projects/sourcecodepro.adobe/

**Comment by kyleholzinger** [comment]
I know this is an old issue, but the download link is no longer clickable on the link provided on the README. I had to go to [this link](http://www.adobe.com/jp/devnet/opentype/afdko.html) (the japanese version of devnet) to download it

**Comment by miguelsousa** [comment]
@kyleholzinger we're aware of the problem, thanks. https://github.com/adobe-type-tools/afdko/issues/175

**Comment by kyleholzinger** [comment]
Ah my bad! Somehow missed that issue.
