### ISSUE TITLE
Line height vs. Block Char height

### ISSUE THREAD

**Issue by HoffmannP** [adobe-fonts/source-code-pro#57]
The Block Characters (mostly used to draw primitives in TUIs) are not fitting together as they are not as high as the line height - the Border Characters do, so it seems to be possible. See image below
![pyd78n2q](https://f.cloud.github.com/assets/2119742/832457/616d75b4-f258-11e2-8374-0d3e1f0931e9.png)

**Comment by eevee** [comment]
For posterity: looks like this was fixed in v2.015 (1.035 italic), released on May 2.  Thank you!  :)
