### ISSUE TITLE
Italic shapes

### ISSUE THREAD

**Issue by greedy** [adobe-fonts/source-code-pro#6]
It would be great to have italic shapes too. Auto-italics will wreak havoc on characters like `\` `/` and `|`.

**Comment by mttrs** [comment]
Looking forward to the Italic shape this year!

**Comment by pauldhunt** [comment]
It’s been a year since Teo started on the italics, and I am now putting the finishing touches on the next version of the family. Thank you everyone for being patient, I hope that the wait will have been worth it.

**Comment by acusti** [comment]
Woooooooooo! Like :christmas_tree: in June!

**Comment by pauldhunt** [comment]
more like July. 😁

**Comment by Melindrea** [comment]
From what I've seen (I'm using a beta version in Mac Scrivener) it is gorgeous =) Thank you so much!

**Comment by yoshuawuyts** [comment]
@pauldhunt amazing! :tada: Will it by any chance also be released on [google fonts](https://www.google.com/fonts)?

**Comment by pauldhunt** [comment]
of course, I expect google to pick them up, unless they have an issue with the character set discrepancy (Greek and Cyrillic missing from the italics).

**Comment by rayshan** [comment]
:+1: it's the only thing preventing me from switching to source code pro full time. Thanks for the hard work!

**Comment by lucidlemon** [comment]
+1

**Comment by Francisc** [comment]
Closed? Hm, guess this means Italics have landed!
![celebration](https://cloud.githubusercontent.com/assets/699657/8706619/76704ab0-2b39-11e5-93df-7ca395b2ac9c.gif)

**Comment by miguelsousa** [comment]
@Francisc pretty much. The official release is on Friday, but you can already find the fonts in the `release` branch.

**Comment by darrenhaken** [comment]
Amazing work






On Wed, Jul 15, 2015 at 11:55 AM -0700, "Miguel Sousa" <notifications@github.com> wrote:












@Francisc pretty much. The official release is on Friday, but you can already find the fonts in the release branch.

**Comment by Francisc** [comment]
That's so awesome, thanks Miguel.

**Comment by Melindrea** [comment]
So glad about this, thanks for making it happen =)

**Comment by joaoevangelista** [comment]
Wow! My eyes thanks you guys!

**Comment by pauldhunt** [comment]
Resolved in the latest release:
https://github.com/adobe-fonts/source-code-pro/releases/tag/2.010R-ro/1.030R-it

**Comment by Francisc** [comment]
Look at all the italics!!!
![joy](https://cloud.githubusercontent.com/assets/699657/8765352/8cdcf40e-2e10-11e5-977f-65d53cae2478.gif)

**Comment by mretondo** [comment]
Thanks for all the hard work.
