### ISSUE TITLE
Issue with Italic style on Android Studio

### ISSUE THREAD

**Issue by thuytrinh** [adobe-fonts/source-code-pro#75]
Firstly, I really love this beautiful font and very highly appreciate you guys' work. Lately I changed the typeface in Android Studio into Source Code Pro and encountered this issue very often. Sometimes it happens, sometimes it doesn't. I'm not sure if it's due to the IDE itself or the font.

![screen shot 2014-08-23 at 9 08 34 am](https://cloud.githubusercontent.com/assets/1214816/4019436/c73e44d8-2a6d-11e4-966c-04ce59414777.png)

**Comment by jahunt1** [comment]
I was able to resolve this issue on OS X Yosemite by uninstalling the open type fonts and installing the true type fonts. I also dropped the .ttf files in the JVM directory based on comments in the discussion for Issue #6. The JVM font directory on my machine is: /System/Library/Java/JavaVirtualMachines/1.6.0.jdk/Contents/Home/lib/fonts.
