### ISSUE TITLE
rightward-shifted vertical bar in italic style (beta v.1.002)

### ISSUE THREAD

**Issue by csrhodes** [adobe-fonts/source-code-pro#76]
![screenshot from 2014-09-01 12 11 05](https://cloud.githubusercontent.com/assets/1670142/4107560/7daad17a-31c9-11e4-886f-86bcb3961771.png)
Hi,

Using the beta v1.002 of the Italic shapes (along with the released version of the upright shapes), I notice that the vertical bar character renders differently in the italic variant compared with the uprights.  I use emacs on Debian Linux, so it's possible that this is due to some defect of my font rendering chain, but just in case I thought I would report it here.  I'm attaching a screenshot to this report to show what I mean; I hope it's clear, but in case there's anything else you need me to do to demonstrate the effect, just let me know.

(I also don't know if this is a deliberate design decision.  For what it's worth, here the italic vertical bar appears crisper, but perhaps slightly too wide).

In any case, thank you for the fonts.

**Comment by pauldhunt** [comment]
In continuing to work on the italic fonts it appears that the vertical bar characters will align with those of the upright fonts, but they will remain vertical, as well as lighter and unsloped.
