### ISSUE TITLE
Using Source Code Pro, guides not positioned correctly in Sublime Text

### ISSUE THREAD

**Issue by renier** [adobe-fonts/source-code-pro#79]
Sublime Text can show _guides_ to make it easier to see the beginning and the end of a block of code. Like this:

![screen shot 2014-11-15 at 10 36 47 am](https://cloud.githubusercontent.com/assets/139994/5058020/ac2fa898-6cb3-11e4-9db9-fa3605a39aec.png)

That is using saxMono as the font. The guides work as expected. This screenshot is using Source Code Pro:

![screen shot 2014-11-15 at 10 37 49 am](https://cloud.githubusercontent.com/assets/139994/5058025/d5e4e6b2-6cb3-11e4-8c78-e97fc99afe56.png)

Some of the guides are not at the right places. I believe this has to do with how Sublime Text calculates where they should be based on the space the font blocks are taking. Could this be an issue with the font? Other fonts I have tried work fine.

**Comment by pauldhunt** [comment]
I have no idea what variable Sublime Text uses to determine this behavior, therefore I am at a loss as to what I could do to change the behavior for SSC.

**Comment by pauldhunt** [comment]
I am closing this issue until someone can give me concrete information on what actually needs to be fixed at the font level here.
