### ISSUE TITLE
Has Source Code Pro development stopped?

### ISSUE THREAD

**Issue by Francisc** [adobe-fonts/source-code-pro#84]
Hello,

I really enjoy working with this font and I'm a bit worried about the lack of recent activity, or anyway commit activity that is visible in this repo.

Can you say if there's a future for Source Code Pro?

**Comment by Francisc** [comment]
GitHub doesn't notify on your own issues if you set the whole project to "Ignoring". Good call, GitHub.

Anyway, why was development moved there? I'm just curious.

**Comment by miguelsousa** [comment]
It didn't move. Paul is the main designer/developer. He'll merge his work when he's done. =

**Comment by Francisc** [comment]
Thanks.
