### ISSUE TITLE
What is the most "correct" way for this font to look like on Windows?

### ISSUE THREAD

**Issue by mxxcon** [adobe-fonts/source-code-pro#86]
It seems like if I install OTF and TTF versions, they look very different.
Additionally, in Sublime Text 3 if I change rendering modes with `"font_options":` parameter, each of these changes how the font looks: `gray_antialias`, `subpixel_antialias`, `gdi` and `directwrite`.

There's probably some sort of a way font's creators intended it to look like, so which of these combinations is the right one for Windows 8.1

**Comment by pauldhunt** [comment]
I’ve tried to design the fonts to work well under a range of rendering conditions, but obviously some are better than others. If you could post some images of different rendering scenarios that you’re looking at, I could comment on which look best to my eye.

**Comment by mxxcon** [comment]
Here are all the variations.(some might be duplicates)
http://mxxcon.trvx.com/fonts/

**Comment by pauldhunt** [comment]
I’ve looked through these and find that the the TTF fonts with subpixel rendering seem to work best. All of the OTF renderings seem to have the dot of the i falling to the right, which is not a huge issue but I would find it distracting. In fact, the TTF fonts exist mainly to provide better rendering on Windows systems and were hinted specifically with subpixel rendering in mind, so I’m not totally surprised that these look best. However, I was under the impression that DirectWrite did a better job at rendering OTF, but it seems that the TTF + subpixel rendering is still better.

**Comment by mxxcon** [comment]
So is it a bug in the font itself or Windows' font support with how letter `i` looks in OTF?
Also between "Regular" and "Medium" TTF fonts with subpixel have the most noticeable difference in `"` symbol and capital `P` letter.

**Comment by pauldhunt** [comment]
The dot of the i is centered mathematically (and visually) over the stem. I have not noticed any rendering issues on Mac, which is what I use most and the problem is not visible in the TTF fonts. I do not know much about DirectWrite rendering, but it seems that it is somehow doing the wrong thing here.

The difference between Regular and Medium is very slight and probably less noticeable at smaller sizes. Choose whatever one gives the impression that you want to make.
