### ISSUE TITLE
IntelliJ IDEA中部分窗口下中文显示有误

### ISSUE THREAD

**Issue by xiangyunwangluo** [adobe-fonts/source-code-pro#87]
![qq 20150122112508](https://cloud.githubusercontent.com/assets/6205729/5850074/75eb833c-a229-11e4-840e-e9cf2934908c.png)
![qq 20150122112605](https://cloud.githubusercontent.com/assets/6205729/5850073/75eb74e6-a229-11e4-914e-23c98640c7c2.png)

如上述两张截图的中的位置处

**Comment by miguelsousa** [comment]
Source Code Pro does not support Chinese. You must be looking for [Source Han Sans](https://github.com/adobe-fonts/source-han-sans).
