### ISSUE TITLE
SourceCodePro-BoldIt not listed as italics

### ISSUE THREAD

**Issue by MikeBadescu** [adobe-fonts/source-code-pro#89]
On Windows 7, SourceCodePro-BoldIt.otf (from SourceCodePro-Italics-BETA_v1002.zip) has listed in its properties that it is only a Bold font (and not an Italics one too). Thus, Windows believes that SourceCodePro-BoldIt.otf is the same font as SourceCodePro-Bold.otf and displays only the font that is installed last.

**Comment by pauldhunt** [comment]
Thanks for reporting, I’ve fixed this in the code and this will be fixed in the official release.
