### ISSUE TITLE
PaulVersionCurrent branch: Some characters have wrong width

### ISSUE THREAD

**Issue by codeman38** [adobe-fonts/source-code-pro#90]
In the PaulVersionCurrent branch, the following characters have an advance width that's something other than the expected 600:

* **Roman weights:** guillemotleft, guillemotright, paragraph, quotedbl, quotedblbase, quotedblleft, quotedblright, uni203C, uni2116
* **Italic weights:** guillemotleft, guillemotright, quotedbl, quotedblbase, quotedblleft, quotedblright, uni02C1, uni02D0, uni02D1, uni02DE, uni02E0, uni203C, uni2116

**Comment by codeman38** [comment]
Working on a merge request for this right now.

**Comment by codeman38** [comment]
Pull request opened - see pauldhunt#5.

**Comment by pauldhunt** [comment]
Thank you for reporting but I will likely make these changes myself as I am madly shuffling things around at the moment.

**Comment by codeman38** [comment]
OK, thanks. I'll close the pull request but leave a branch open for my own experimentation, then.
