### ISSUE TITLE
PaulVersionCurrent branch: 'paragraph' glyph fails to interpolate in Roman

### ISSUE THREAD

**Issue by codeman38** [adobe-fonts/source-code-pro#91]
In the PaulVersionCurrent branch, the Roman master fonts both include a glyph for `paragraph`, but interpolation appears to fail on that glyph when the instances are being generated:

```
2015-04-06 20:08:28,116 MutatorMath Errors calculating 1 glyphs:
2015-04-06 20:08:28,117 MutatorMath paragraph
```

Sure enough, the `<outline>` tag in the resulting `paragraph.glif` for each instance is completely empty.

**Comment by codeman38** [comment]
Issue seems to be that the contours are in opposite order between the two masters - the bar is first in SourceCodePro_0, but the hump is first in SourceCodePro_1.

**Comment by pauldhunt** [comment]
Yes, I know how to troubleshoot these things. 😄 FYI: this branch is a development branch and as such susceptible to frequent changes: it will likely be a moving target for you to keep reporting issues with this branch.
