### ISSUE TITLE
Missing cyrillic characters in collapsed region on 1C:Enterprise platform

### ISSUE THREAD

**Issue by gruk0** [adobe-fonts/source-code-pro#92]
Missing cyrillic characters in collapsed region on platform "1C:Enterprise 8.3 (8.3.5.1248)". Windows system fonts with cyrillic support work fine.
![image](https://cloud.githubusercontent.com/assets/11936056/7130238/0cb73030-e29f-11e4-901d-c620b04aac77.png)

**Comment by miguelsousa** [comment]
@gruk0 Currently the fonts don't support Cyrillic. If you're seeing Cyrillic characters it's because the software you're using is doing font-fallback, i.e. replacing the font you've specified by another font that includes the missing characters.
