### ISSUE TITLE
Generate Chocolatey package for SourceCodePro

### ISSUE THREAD

**Issue by bitcrazed** [adobe-fonts/source-code-pro#93]
Could you generate a Chocolatey package for SourceCodePro as part of the standard build process?

Chocolatey is a popular package manager for Windows (similar to apt-get) which many Windows users use to automate setup & configuration of their machines & environments. Chocolatey packages contain metadata to describe how Chocolatey can download & install (or uninstall) a variety of tools, apps, etc. 

Alas, the current SourceCodePro package owner has not updated the package to point at SCP's new home on GitHub and, thus, we Chocolatey users are unable to install SCP as part of our automated setup mechanisms :(

I'm reaching out to the package owner asking them to update the packge to point at SCP's new release branch on GitHub, but would you be interested in taking over the SCP Chocolatey package and keeping it up to date as part of your build process?

**Comment by miguelsousa** [comment]
Hi Rich. We want to be supportive as much as possible, but we don't have the expertise, manpower or bandwidth to be responsible for any packaging solutions beyond the files we put out in the release branch.
If it's just a matter of adding some metadata files to our repository, go ahead make a PR and we'll merge it. If, on the other hand, the process requires more involvement from us, I'm sorry to say we can't take that on. I hope you understand.

**Comment by bitcrazed** [comment]
Hey Miguel. Thank for considering.

Generating a Chocolatey package is pretty brain-dead simple and am sure could be incorporated into your build process with little/no impact. I'll fork and iterate on this and get a PR out to you by mid-next week if I can.

**Comment by digitaldrummerj** [comment]
I just took over as the maintainer of the already existing Chocolatey package.  I have submitted a new version to Chocolatey for the latest release.  https://chocolatey.org/packages/SourceCodePro/2.010.0 

The source code for the Chocolatey package is at https://github.com/digitaldrummerj-chocolatey/ChocolateyPackages/tree/master/SourceCodePro  .  

To create this package install Chocolatey using the command on their home page at http://chocolatey.org .  Then from the SourceCodePro folder update the nuspec file to a new version number, update the download url in the tools\ChocolateyInstall.ps1 file, and then from the command line run choco pack within the SourceCodePro directory.  The choco pack command will create the nupkg file that chocolatey needs.  

Once it is created you can test it out by running the command: choco install SourceCodePro -source %CD% .  If you already have it installed, run choco upgrade SourceCodePro -source %CD%.

When you are done testing, you just need to upload it to the Chocolatey web site for approval.  

I would be more than happy to add someone from Adobe as an additional maintainer for the package if you guys would like to make this part of your standard release process.

**Comment by miguelsousa** [comment]
@digitaldrummerj thanks for the offer and for the setup work you did. If supporting Chocolatey was just a matter of adding a simple file to our repository, I'd make it part of our release process. But from your instructions I see that the process is more involved than I expected. I'm sorry, but we won't be able to take on the task of generating Chocolatey packages.

**Comment by bitcrazed** [comment]
@digitaldrummerj Great news - congrats on taking over the Chocolatey package. I got completely swamped and didn't manage to free-up cycles to work on this; glad you did :grin:

@miguelsousa What would define as a process that is sufficiently simple for you to incorporate into your standard release mechanism? Happy to lend a hand here.

Now that Windows 10's OneGet package manager supports multiple package sources including Chocolatey, I'd expect an increase in the number of Windows users who'd be interested in installing the latest SourceCodePro font in an automated manner, so it'd be great to keep the CHocolatey package pointing at the latest SCP build.

**Comment by miguelsousa** [comment]
> What would define as a process that is sufficiently simple for you to incorporate into your standard release mechanism?

One that does not require us to manually generate and upload new Chocolatey packages every time new font versions are released. We're as swapped as you :grin:

**Comment by bitcrazed** [comment]
LOL :smile: How do you build new releases? Could we help augment the build process?

**Comment by miguelsousa** [comment]
@bitcrazed if you can figure out an automated process that hooks into the [`release` branch](https://github.com/adobe-fonts/source-code-pro/tree/release) —which is where we put the release font files in various formats — we can look into making that part of our release tasks.
