### ISSUE TITLE
Greek and Cyrillic character support release

### ISSUE THREAD

**Issue by parisk** [adobe-fonts/source-code-pro#94]
In #48 it was stated on December 2014 that on the next release of the font Greek and Cyrillic characters were to be introduced.

Is there any specific time span in which you aim to make this release? I checked out the releases page of this repo and the last release was in July 2014.

Checked out the project website also at http://adobe-fonts.github.io/source-code-pro/ and no Greek or Cyrillic characters seem to render appropriately.

**Comment by eskin** [comment]
+1
i am waiting only for this

**Comment by pauldhunt** [comment]
This is not far out now. You can check out my fork for updates in regards to this. There are UFO sources which should compile with the AFDKO tools, but no compiled fonts in this repo. You can check our the work so far if you have a font editor that supports UFO.
https://github.com/pauldhunt/SourceCodePro/tree/PaulVersionCurrent

**Comment by akaspin** [comment]
:+1: 
Funny. Look at #48. Epic :-)

**Comment by pauldhunt** [comment]
The uprights in the next release will feature support for Greek and Cyrillic, I expect that new fonts will be available in July.
