### ISSUE TITLE
Broken TT hints for Yeru, ya, clickalveolar in dev branch

### ISSUE THREAD

**Issue by codeman38** [adobe-fonts/source-code-pro#95]
In the PaulVersionCurrent branch, commit fc308b6 claims that TT hinting is "all done ... for now". However, `Yeru` (Ы) and `ya` (я) are distorted in the Regular weight, and `clickalveolar` (ǂ) is completely misshapen in all weights:

![badhints](https://cloud.githubusercontent.com/assets/386563/8038013/f73681ec-0dce-11e5-85dd-82aab9e09ac0.png)

**Comment by pauldhunt** [comment]
Thanks for your report. I will be sure to fix these as part of our QE process which will be happening hopefully this week. Everything should be resolved in the official main branch of SCP once we have verified everything.
