### ISSUE TITLE
Source Code Pro shows incorrect tab widths for some sizes in Xcode

### ISSUE THREAD

**Issue by scztt** [adobe-fonts/source-code-pro#97]
May not be a Source Code Pro problem - if not, at least this provides a relevant workaround

In Xcode, for many regular integer point sizes of SCP, there appears to be a rounding error in determining tab position, such that some tab characters will be reduced to seemingly a sub-pixel width rather than jumping to the next tab-stop, ruining e.g. tab alignment of variable definitions. This doesn't appear to be a problem with any of the other common programming fonts I tried apart from SCP. At a pt size of 12, in any weight, the test string doesn't stay aligned consistently, starting at line 24.

A size of 12.5 seems to be the smallest size greater than 12 that avoids whatever rounding error causes the tab mis-sizing. You can test other fonts / find a size that works experimentally, by checking the test string (with a tab width of 4) - you have to change the pt size of ALL source editor styles, AND THEN close and reopen the document for this to work correctly (all ='s should be aligned).

This seems specifically an interaction between SCP and Xcode, as I don't see it in other editors or with other fonts, but it's definitely a bad problem - without the workaround, tab alignment that looks correct in Xcode w/ SCP will almost surely be incorrect in any other editor.

```
A                                            = true;
AB                                           = true;
ABC                                          = true;
ABCD                                         = true;
ABCDE                                        = true;
ABCDEF                                       = true;
ABCDEFG                                      = true;
ABCDEFGH                                     = true;
ABCDEFGHI                                    = true;
ABCDEFGHIJ                                   = true;
ABCDEFGHIJK                                  = true;
ABCDEFGHIJKL                                 = true;
ABCDEFGHIJKLM                                = true;
ABCDEFGHIJKLMN                               = true;
ABCDEFGHIJKLMNO                              = true;
ABCDEFGHIJKLMNOP                             = true;
ABCDEFGHIJKLMNOPQ                            = true;
ABCDEFGHIJKLMNOPQR                           = true;
ABCDEFGHIJKLMNOPQRS                          = true;
ABCDEFGHIJKLMNOPQRST                         = true;
ABCDEFGHIJKLMNOPQRSTU                        = true;
ABCDEFGHIJKLMNOPQRSTUV                       = true;
ABCDEFGHIJKLMNOPQRSTUVW                      = true;
ABCDEFGHIJKLMNOPQRSTUVWX                     = true;
ABCDEFGHIJKLMNOPQRSTUVWXY                    = true;
ABCDEFGHIJKLMNOPQRSTUVWXYZ                   = true;
ABCDEFGHIJKLMNOPQRSTUVWXYZa                  = true;
ABCDEFGHIJKLMNOPQRSTUVWXYZab                 = true;
ABCDEFGHIJKLMNOPQRSTUVWXYZabc                = true;
ABCDEFGHIJKLMNOPQRSTUVWXYZabcd               = true;
ABCDEFGHIJKLMNOPQRSTUVWXYZabcde              = true;
ABCDEFGHIJKLMNOPQRSTUVWXYZabcdef             = true;
ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefg            = true;
ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefgh           = true;
ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghi          = true;
ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghij         = true;
ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijk        = true;
ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijkl       = true;
ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklm      = true;
```

**Comment by pauldhunt** [comment]
hmmmm this seems similar to #79, not sure what is going on there. will try to investigate.

**Comment by tommythorn** [comment]
FWIW, the above looks perfect in Emacs (on Mac).
