### ISSUE TITLE
[Brackets] Issues with the beta fonts with russian/cyrillic/greek support

### ISSUE THREAD

**Issue by abose** [adobe-fonts/source-code-pro#98]
We recently integrated the beta version of the fonts provided with  Russian/ Cyrillic/ Greek support. Our loc team is currently validating the fonts, Created this issue to track the issues we encountered.
Tagging @rawat11 to provide more details

**Comment by rawat11** [comment]
The current font integration renders Greek and Russian characters in a better manner

Updating the screenshots : 
![2015-06-24 11_11_34-p__brackets_release 1 4_cyrillic test data_2015-06-24 10_18_57- index html get](https://cloud.githubusercontent.com/assets/10069885/8323430/da820c84-1a61-11e5-99ea-56df7953daa7.png)


For the Cyrillic support, the early cyrillic characters along with some of the extended and supplement characters, the fonts are displayable and does not break

Test data Cyrllic early and extended characters
ӐӑӒӓӘәӚӛӔӕБбВвГгҐґЃѓҒғӶӷҔҕДдЂђЕеЀѐЁёӖӗҼҽҾҿЄєЖжӁӂҖҗӜӝЗзҘҙӞӟӠӡЅѕИиЍѝӤӥӢӣІіЇїӀӀЙйҊҋЈјКкҚқҞҟҠҡӃӄҜҝЛлӅӆЉљМмӍӎНнҤҥҢңӉӊӇӈЊњОоӦӧӨөӪӫҨҩПпҦҧРрҎҏСсҪҫТтҬҭЋћЌќУуЎўӲӳӰӱӮӯҮүҰұФфХхҲҳҺһЦцҴҵЧчӴӵҶҷӋӌҸҹЏџШшЩщЪъЫыӸӹЬьҌҍЭэӬӭЮюЯя

![2015-06-24 11_18_15- untitled-1 getting started - brackets](https://cloud.githubusercontent.com/assets/10069885/8323548/b20d2ca0-1a63-11e5-9441-98bbea4b60db.png)


Some of the cyrillic characters were not supported at all in the editor

testdata : Ѿ Ҿ

![2015-06-24 11_27_23- untitled-1 getting started - brackets](https://cloud.githubusercontent.com/assets/10069885/8323586/0bf90266-1a64-11e5-87fb-d23ba05ddf86.png)


Please check the following let us know if we can try the same with some more charcter set

For other cyrllic supported languages like : serbian, ukranian it's working fine

**Comment by miguelsousa** [comment]
@rawat11 

The fonts support the following Cyrillic characters:
**АБВГДЕЖЗИЙКЛМНОПРСТУФХЦЧШЩЪЫЬЭЮЯ
ЀЁЂЃЄЅІЇЈЉЊЋЌЍЎЏѢѲѴҐҒҖҘҚҠҢҪҮҰҲҶҺӀӁӐӔӖӘӢӦӨӮӲ
абвгдежзийклмнопрстуфхцчшщъыьэюя
ѐёђѓєѕіїјљњћќѝўџѣѳѵґғҗҙқҡңҫүұҳҷһӏӂӑӕӗәӣӧөӯӳ**

The above characters will enable support for the following Cyrillic-based languages:
Balkar, Belarusian, Bulgarian, Erzya, Karachay, Kumyk, Macedonian, Moksha, Nanai, Nogai, Russian, Rusyn, Serbian, Ukrainian, Abaza, Adyghe, Agul, Avar, Bashkir, Buryat, Chechen, Chuvash, Crimean Tatar, Dargin, Dungan, Ingush, Kabardian, Kalmyk, Karakalpak, Kazakh, Khinalugh, Komi, Kyrgyz, Lak, Lezgian, Moldovan, Mongolian, Ossetian, Rutul, Tabasaran, Tajik, Tat, Tatar, Turkmen, Tuvan, Uyghur and Uzbek.

Many of the characters that you included in your test data are not present in the fonts and are only needed for minority languages or archaic texts.

**Comment by yurikhan** [comment]
@rawat11, @miguelsousa If you are seeking comments, here’s my stand as a native Russian speaker.

The rendering of Cyrillics on the first screenshot is unpleasant. This may be a hinting problem and it may be platform-dependent; I am evaluating only this screenshot here.

* н, у, х, ц, ч, ш: The tops of vertical or diagonal strokes need to reach the x-height; in the screenshot, they are 1px too short. After this is fixed, for at least н and х, check that the middle stroke and the intersection are at or slightly above the geometric center.

* г, м, п, т: The vertical stems’ bottoms hover 1px above the baseline. Should stand firmly.

* в, з, э: The top half is bigger than the bottom. Should be vice-versa.

* ё, ф, щ, ъ: These letters are not present in the sample. щ is prone to the same issue as ш.

**Comment by rawat11** [comment]
@yurikhan But that's the font property that's how it's rendering it on the editor.
Could you please tell if the context of the characters is getting changed by the font use. 

@miguelsousa Yes, I got your point but the font support has been added to make sure that we support the cyrillic character set, and there are some characters which the font is not able to render properly since it does not support it.

**Comment by yurikhan** [comment]
@rawat11 What do you mean by context? If you mean to ask if letter shapes change depending on the surrounding characters like in Arabic or some Indic scripts — no, in Cyrillic they don’t. Any issue that is visible on your sample text will be seen on any other text.

**Comment by rawat11** [comment]
@yurikhan By context i mean the meaning conveyed by the characters

**Comment by yurikhan** [comment]
@rawat11 I think I understand you now: you are asking if the defects in the letter rendering change the meaning of text. No, they don’t, it just looks sloppy.

**Comment by codeman38** [comment]
It may be worth trying the TTF version of Source Code Pro instead of the OTF. Windows' rendering of CFF fonts, though better than it used to be, is still not so good.

**Comment by yurikhan** [comment]
If it were solely a Windows OTF rendering issue, it would affect Latin letters too. However, the screenshot does not indicate that.

**Comment by leeoniya** [comment]
@yurikhan is correct. if those screenshots are any indication of how Russian will look with the new SCP, it looks terrible. The tops of all lowercase letters must be aligned, otherwise it looks as if a different size font has been used for each character - no different than English and I suspect many other languages.

![735a1623-9bb3-11e3-bc74-14dae9b62a82](https://cloud.githubusercontent.com/assets/43234/8334498/e40dda16-1a5d-11e5-8a83-3a85a5f5d910.jpg)

**Comment by yurikhan** [comment]
OK, I have downloaded those font files and I don’t seem to have the problem on X11/GNU/Linux.

**Comment by pauldhunt** [comment]
I’m tracking these issues. I will double check the cyrillic hinting to see if i can find out what is causing the issue with the bouncy Cyrillic letters. In fact, I may have fixed these already. @rawat11 I can send you updated files if you like.

**Comment by erniemarch** [comment]
I hope so (and think so). I don’t recall seeing any x-height bouncing on the waterfall proofs I looked at

**Comment by nethip** [comment]
@pauldhunt Sure send us the updated files. We will try them out. 

@sprintr had observed that the the dot in the small `i` is now getting combined with the stem. Please see the screenshot below.

![image](https://cloud.githubusercontent.com/assets/1577184/8346639/44087a38-1b1d-11e5-93b0-f5b6e615eb78.png)

For reference: https://github.com/adobe/brackets/pull/11301#issuecomment-115018378

**Comment by rawat11** [comment]
@nethip Updating the MAC screenshots : the font rendering is bad on MAC

before increasing the font size

![1](https://cloud.githubusercontent.com/assets/10069885/8346688/1682a6a0-1b1e-11e5-9217-9c614cba7983.png)


After increasing the font size

![mac](https://cloud.githubusercontent.com/assets/10069885/8346692/2593eac8-1b1e-11e5-9b7a-d7cf62acbf7b.png)


For the same data on Windows, the difference is evident

![cyrillic](https://cloud.githubusercontent.com/assets/10069885/8346695/336b44fc-1b1e-11e5-8918-f630424f2e25.png)

**Comment by rawat11** [comment]
@pauldhunt Yes please send us the files

**Comment by yurikhan** [comment]
@rawat11 You might want to use real text for tests. Here’s a pangram for you: Съешь ещё этих мягких французских булок, да выпей же чаю.

**Comment by frankrolf** [comment]
It is worth noting that those screenshots will look differently depending on the environment they are displayed in. 

I just noticed: 
When just clicking on them for preview them in Safari, there seems to be some kind of image-smoothing going on. Downloading the images and opening in Preview makes a pixel-to-pixel comparison possible; and is better for evaluating actual font rendering issues.

@rawat11 Please don’t just paste the whole Unicode range for Cyrillic into the preview string.
Apart from containing many unsupported and archaic characters, it is very hard to judge the real-world appearance of text.

Just use some real text, like this:
https://ru.wikipedia.org/wiki/Adobe_Systems

Or pangrams, as mentioned above. Some more are here:
http://russiangrammar.tumblr.com/post/47052935056/russian-pangrams

**Comment by nethip** [comment]
@sprintr @pauldhunt About the dot of the small `i` appearing closer to the stem, this seems to be happening with OTF font version of Source Code Pro and not with the TTF version. So it looks like it is safe to go with TTF font. I really liked the OTF font rendering with Source Code Pro on Windows but as per @pauldhunt 's advice on "stick to TTF if using TTF" we must be use TTF format.

@abose Please update [abose/SourceCodeProNew](https://github.com/adobe/brackets/tree/abose/SourceCodeProNew) branch with the TTF version of updated Source Code Pro.

**Comment by pauldhunt** [comment]
@nethip is the i (and i assume the j) dot the only diacritic that is collapsing in this manner? If so, I can try shifting the dot accent up to see if we can remedy this issue in the OTF fonts. However, as @yurikhan points out that the OTF rendering in the platform you are using has the additional problem of rendering the upper portion of some lowercase letters (в, з, э) lager than the bottom.

**Comment by sprintr** [comment]
@pauldhunt Yes, j and i are the only characters having problem, other than that its rendering using OTF is really awesome on Windows.

**Comment by nethip** [comment]
@sprintr @pauldhunt Looks like fixing the `i` and `j` should be good for the en character but I am not sure about any issues with other character sets, as I would not understand the correctness of the glyphs in other locales. So I am not sure if just by fixing 'i' and 'j' diacritics should be a "good to go" with OTF version. @rawat11 Do you think we could get some help from our loc testing vendors on this?

@yurikhan Hey thanks a lot for jumping in and testing the fonts and providing your valuable inputs. From your comments above, if I understand correctly, the issues you have reported (https://github.com/adobe-fonts/source-code-pro/issues/98#issuecomment-114816917) are not seen with TTF fonts right?

The entire exercise we are going through, by updating Source Code Pro to the latest version, is to add better character set support to Brackets with no/minimal side effects, be it TTF/OTF. For now my recommendation is to go via the TTF route. Thoughts?

**Comment by yurikhan** [comment]
@nethip No, that’s not what I said.

As far as I understand, the original screenshot was made with the OTF font from Brackets on Windows, and it exhibits the issue.

Later, I downloaded a copy of the OTF fonts from Brackets repository, had a look at them in Mousepad on GNU/Linux, and did not experience the issue.

I have not tested and will not personally test the TTF+Windows combination, but if you show me a screenshot, I will tell if the issues are present or not.

**Comment by rawat11** [comment]
@nethip surely..we are looking into that.

**Comment by nethip** [comment]
@yurikhan Sure! We will try to post the screenshots. @rawat11 Could you help us with taking the screenshots with the latest TTF fonts? Also please use @frankrolf 's [advice](https://github.com/adobe-fonts/source-code-pro/issues/98#issuecomment-115160308) on which characters we need to screenshot. Thanks!

**Comment by rawat11** [comment]
@nethip Below are the screenshots with the latest ttf fonts. I have used the data provided by @frankrolf .

![1](https://cloud.githubusercontent.com/assets/10069885/8375717/84c3f4ac-1c1d-11e5-9af7-500ca2f2f3cd.png)
![2](https://cloud.githubusercontent.com/assets/10069885/8375718/84c6ad1e-1c1d-11e5-8ca6-763ad99dd265.png)

Please have a look at them

**Comment by rawat11** [comment]
@yurikhan I am updating the screenshots for MAC with ttf fonts.
Above scrrenshots are the one's tested on Windows

![screen shot 2015-06-26 at 4 44 52 pm](https://cloud.githubusercontent.com/assets/10069885/8376147/8b670264-1c21-11e5-8180-990cd2d4a165.png)
![screen shot 2015-06-26 at 4 44 58 pm](https://cloud.githubusercontent.com/assets/10069885/8376148/8e08bd32-1c21-11e5-9aa9-432ad61e798f.png)

**Comment by yurikhan** [comment]
The last four screenshots are OK.

**Comment by sprintr** [comment]
@nethip Agreed, we should stick to TTF for the time being, while problems with i, j and other characters of the supported unicode set are solved.

**Comment by rawat11** [comment]
@yurikhan That mean's stick to ttf fonts

**Comment by abose** [comment]
@rawat11 we have switched the fonts to ttf in the latest pr.

**Comment by rawat11** [comment]
@abose Yes these Screenshots are captured on ttf

**Comment by rawat11** [comment]
@nethip @abose Our team has confirmed that we are good to go with the the ttf fonts.
Also, there has been little doubts on the japanese fonts (the characters in it look like Japanese (for Hiragana and Katakana, they displayed OK as Japanese), but seem garbled for Kanji (Chinese characters))

I am updating the SS

![4-japanese-win](https://cloud.githubusercontent.com/assets/10069885/8424114/ce714d96-1f12-11e5-96ea-419774a0c131.png)

**Comment by miguelsousa** [comment]
@rawat11 the Japanese fonts discussion probably doesn't belong here.

**Comment by abose** [comment]
@rawat11 we will be integrating the fonts in brackets today then. Thanks all for helping :+1:
